### ISSUE TITLE
Decimal formatting for data

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#115]
General rules for number of decimal places shown..

- estimates: 0
- MOE: 0
- CV: 1
- percent: 1
- percent MOE: 1

**Comment by EricaMaurer** [comment]
Exceptions to the rule shown in this file..
[Data Dictionary_0610-1115 database_decimal notes.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cc958e22c2a7a08cfdb64caa5ce28d161671227949f27a21d0a32cbe567a030e1c1bc3150d0c1da1a8d53bf8e97825c94e17ff912f002e936e55beb2901ab654b274894bd4b4b4821894ec3d25e1df8a4b3a1e01119be34f77f1c71f9705af01b40f47ae013764ec77337c4e9d177429686520adfecd1b.xlsx)

**Comment by JoelAAlvarez** [comment]
Added a decimal rules field to the Census data dictionary and uploaded file
