### ISSUE TITLE
Charts follow tables

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-nyc-factfinder#126]
The tables should appear above the charts in the reports.

**Comment by andycochran** [comment]
This change will directly effect #109, which might allow the CSS-only solution to work.

**Comment by EricaMaurer** [comment]
If possible, the chart will follow the table section it is associated with 

(example: population pyramid would follow "Sex and Age" and come before "Mutually Exclusive Race/Hispanic Origin"

**Comment by andycochran** [comment]
Hmm. This would require a completely different setup. Currently, we have all the data in one table with one header. We'd need to break it up between multiple tables, each with its own header. 

We should talk to users about this. Find out if they want the charts sprinkled throughout the data, or if they'd rather look at the data table and charts separately. 

(Personally, I'd like to be able to see all the charts together to get an overall impression of the report, and dig into the data table without charts in the way.)

**Comment by JoelAAlvarez** [comment]
We just had a discussion on this topic with Joe and Peter this morning. Their preference is to have the charts interspersed throughout the data...charts would come at the end of each sub-section. That said, I don't think it's worth going crazy over. Let's leave them all at the end for now, and we can revisit if opportunity knocks...but not likely.

**Comment by JoelAAlvarez** [comment]
Can someone invite me to be a Github contributor?...thanks.
