### ISSUE TITLE
Centering of default map view

### ISSUE THREAD

**Issue by JoelAAlvarez** [NYCPlanning/labs-nyc-factfinder#132]
Peter Lobo requested that we re-center the default map view to show more of Brooklyn, Queens, and Manhattan.

**Comment by JoelAAlvarez** [comment]
Here is a screenshot of his preferred view...
![PetersPreferredPFFDefaultMapView.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46d8918e269090999decb946b64ff590196001572c02a23e7c91ce29af747204184d52be011a001ea9aacd39aca43979df545fefd53c5d7cce6945a8b88219eb04be248b4b8ca4a0980e91b6697abad2c51a7c0c0f0a88f85734a5984bca5dfe4de54b53a716242e.png)

**Comment by chriswhong** [comment]
Closed by ef68c77046bd15785a27a963c52ed1d88f9678af
