### ISSUE TITLE
User can view Social Report tables

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#138]
This issue describes adding basic table views to the remaining 3 ACS tabs, with all existing functionality (Current/Change over Time, toggle MOEs and Reliability)

(ACS table layouts are repeated across all ACS tabs, refactor demographic table components to reflect this)

**Comment by EricaMaurer** [comment]
Social is too large to attach here

**Comment by CeciliaCY** [comment]
[social.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46fb9b992a838febc3abaf51ab57f5973d047d317c5da67374d7b729ed1a23050b5b4eac470c5a40f8f98d22b4aa2e32db025fb28c341521842f1bbeb98b15be04bb208c4983b1ba824dc4ed2f68.zip)

Social Table Config files

**Comment by CeciliaCY** [comment]
[mockups_and_charts_all_in_one.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46e59b99289793bab0e8b1479b5ef8953b52344c2808af14798bdc27b147394d4d1f0cf31b0d0c00eef39b2eafe3342488585aefd9650b20c23d11aaec871bbb01be29995397f4edd4189fb5646fb2c99d452c1f0c1288fa5c35a79f4dc15af742e94947e9.xlsx)

Mockup

**Comment by chriswhong** [comment]
This is still open, need @allthesignals to investigate why the data for two tables (School Enrollment and Marital Status) are not showing up in the app.
