### ISSUE TITLE
Add Race and Hispanic Origin Chart

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#140]
Bar chart with labels

**Comment by EricaMaurer** [comment]
Mutually Exclusive Race/Hispanic Origin
- Hispanic
- White nonhispanic
- Black nonhispanic
- Asian nonhispanic

Data columns:
- Hsp1P
- WtNHP
- BlNHP
- AsnNHP

**Comment by EricaMaurer** [comment]
duplicate
