### ISSUE TITLE
Changes to Calculations in Demographic Table

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#147]

**Comment by EricaMaurer** [comment]
Calculations to update:

Current:
- number difference: selected area estimate - comparison area estimate
- pctg point difference: selected area percent - comparison area percent

Change over time:
- selected area percent change: numeric change of selected area (2011-2015 - 2006-2010)/selected area 2006-2010 estimate 
- comparison area percent change: numeric change of comparison area (2011-2015 - 2006-2010)/comparison area 2006-2010 estimate
