### ISSUE TITLE
Remove columns from change over time profiles

### ISSUE THREAD

**Issue by JoelAAlvarez** [NYCPlanning/labs-nyc-factfinder#149]
Remove columns showing number and percent for 2006-2010 and 2011-2015 from change over time view whenever comparison is selected -- columns should not appear regardless of whether reliability is shown.

**Comment by chriswhong** [comment]
![nyc_population_factfinder](https://user-images.githubusercontent.com/1833820/33564032-87c2f638-d8e7-11e7-980f-fed9513229e3.png)
