### ISSUE TITLE
User can activate tooltips for more information throughout the app

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#15]
Question mark buttons throughout application to provide explanations on terms or features to users

**Comment by JoelAAlvarez** [comment]
[Tool tips by profile.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46dc9b952fc297a09ffaff41bd1de08626402e7f2c46ef696097ec22ba416f43554d4ba514500b46f8a88b23aee268748a5c0db9d4695b74c23403b0aac04ee155e57dd205d0f4ae805ec1e13724e28a8b4b361704108efe5c3db2d4.xlsx)

**Comment by JoelAAlvarez** [comment]
[Tooltips.pptx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46dc9b952f968ab99cabf301b44fff9e2c4533317346f67275dde77aeb432959570b1aa841585910f9fd8d2ba2bf2e6c981e5ab38532022d8c6853beb2901dbf0bbb258a4b81beb5894cc8ec3f26f5c6.pptx)

**Comment by JoelAAlvarez** [comment]
[Report View tooltips.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46da918a2c9097e9b9e0ba54e449ff9b25522e633a46ef696097ec22ba416f43554d4ba514500b46f8a88b23aee268748a5c0db9d4695b74c23403b0aac04ee155e57dd205d0f4ae805ec1ef3724e28a8b4b371e071f80fb5434b2d4.xlsx)

**Comment by chriswhong** [comment]
All tooltips outlined in the above (minus tooltips on the map controls) were added as of c44302d0d4169f3d20b8fd3f345d72f197d3a205, @EricaMaurer  to replace lorem ipsum with actual tooltips over the next few days.

**Comment by chriswhong** [comment]
Closed by #389
