### ISSUE TITLE
User can view Housing report tables

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#150]

**Comment by EricaMaurer** [comment]
[Uploading H_ACSDatabase_0610-1115.xlsx...]

**Comment by EricaMaurer** [comment]
[H_ACSDatabase_0610-1115.xlsx](https://github.com/NYCPlanning/labs-nyc-factfinder/files/1468876/H_ACSDatabase_0610-1115.xlsx)

**Comment by CeciliaCY** [comment]
[housing.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46e09b8f308b8daecda5fd53b652fa912a5265296b51fa2e2881b17cbe1023590b0b4aac415e0b41f8fd892fafa42062c80d55b98e30063e937f03a6aa8318b500bf218b4883b0b48e49c6e03837aa.zip)

Housing Table Config Files

**Comment by CeciliaCY** [comment]
[mockups_and_charts_all_in_one.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46e59b99289793bab0e8b1479b5ef8953b52344c2808af14798bdc27b147394d4d1f0cf31b0d0c00eef39b2eafe3342488585aefd9650b20c23d11aaec871bbb01be29995397f4edd4189fb5646fb2c99d452c1f0c1288fa5c35a79f4dc15ff74be14b47e9.xlsx)

Mockup

**Comment by CeciliaCY** [comment]
[edits to social and chart tabs.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46ed90933791c3bd80a9ac4ca754f198694729776907ab2a6291a33cbe406843434d0eee1e020a17b8eb8339a3bf6978de5e0fbcd3655720923911acbed61abb05ba24825d99a4fedb1294b7607caddecd5d340c041f83fe5834a0914fcc51f54ae84e52b65e.xlsx)

Latest version of the mockup
