### ISSUE TITLE
User can view Economic Report Tables

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#151]

**Comment by EricaMaurer** [comment]
[Uploading E_ACSDatabase_0610-1115.xlsx...]

**Comment by EricaMaurer** [comment]
[E_ACSDatabase_0610-1115.xlsx](https://github.com/NYCPlanning/labs-nyc-factfinder/files/1468871/E_ACSDatabase_0610-1115.xlsx)

**Comment by CeciliaCY** [comment]
[econo.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46ed97952d8dc1e5cdf9ad4cae58f3806b1c65267001fb2f22d1e27ae71a7f055b5f4eaa155d5b40fcfd8039baa47e21d40854b088270a36d43703adbf881eba00ba278d498db7be8b4ec5fa70.zip)

Economic Table Config Files

**Comment by CeciliaCY** [comment]
[mockups_and_charts_all_in_one.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46e59b99289793bab0e8b1479b5ef8953b52344c2808af14798bdc27b147394d4d1f0cf31b0d0c00eef39b2eafe3342488585aefd9650b20c23d11aaec871bbb01be29995397f4edd4189fb5646fb2c99d452c1f021288fa5c35a79f4dc15df742e64c47e9.xlsx)

Mockup

**Comment by CeciliaCY** [comment]
[edits to social and chart tabs.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46ed90933791c3bd80a9ac4ca754f198694729776907ab2a6291a33cbe406843434d0eee1e020a17b8eb8339a3bf6978de5e0fbcd3655720923911acbed61abb05ba24825d99a4fedb1294b7607caddecd5d340c041f83fe5834a0914fcc50f748e24b5db65e.xlsx)

Latest version of the Mockup

**Comment by chriswhong** [comment]
Closed by #168
