### ISSUE TITLE
"abroad" listed twice in "residence 1 year ago" section

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#183]

**Comment by chriswhong** [comment]
Hi @EricaMaurer, if you are feeling adventurous, you can delete the offending row here and do a pull request:  https://github.com/NYCPlanning/labs-nyc-factfinder/blob/2400f58b6a8f822175361f1a12d23893c3c4da3f/app/table-config/social/residence-1-year-ago.js#L50
