### ISSUE TITLE
Data for renter-occupied housing units not appearing in profile

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#185]
In database as zeros or n/a (current and change views)..

social
- residence 1 year ago
- place of birth
- language spoken at home
- ancestry

housing
- housing tenure: renter-occupied

**Comment by EricaMaurer** [comment]
social variables fixed. 

Data for renter-occupied housing units still  missing.

**Comment by chriswhong** [comment]
This isn't a bug, the data are all `null` for `e` and `m` on Carto.  @EricaMaurer Do we have updated source data?

**Comment by chriswhong** [comment]
Turned out we had the wrong `variablename` for this metric in the metadata table AND in the code, it should be `rochu1` instead of `rochu`.  

I think we may also be using `rochu` in the selection-helpers, so let's check that one.
