### ISSUE TITLE
User should not see 2011-2015 data in change over time, when 2006-2010 data is not available

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#186]
Cells should appear blank for 2006-2010 AND 2011-2015, when 2006-2010 data is not available or applicable

**Comment by chriswhong** [comment]
Add logic to show or hide a table if it is not possible to show change over time (if one of the two time periods has no data, the entire change over time view is moot, so replace the table with a message as to why)
