### ISSUE TITLE
Inflate dollar values from 2006-2010 dataset

### ISSUE THREAD

**Issue by JoelAAlvarez** [NYCPlanning/labs-nyc-factfinder#205]
Inflate 2006-2010 dollar values (already inflated by C. Bureau to 2010 dollar values) to 2016 dollar values by multiplying by 1.1005

There are ten variables that need to be inflated (See attached updated metadata that now includes "InfltnFctr10to16" field)

**Comment by JoelAAlvarez** [comment]
[Data Dictionary_0610-1115 database.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46cc958e22c2a7a08cfdb64caa5ce28d161671227949f27a21d0a32cbe567a030e1c1bbe5d4a1f06a3a3dc78e2a436628f555ee5856f5b25c43519f8ec861fbf07ee258f4b85b2b59850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959f44be64552a6173f6bf43b.xlsx)

**Comment by EricaMaurer** [comment]
Variables to inflate (2006-2010 only)

Economic:
- mdhhinc
- mnhhinc
- mdfaminc
- mdnfinc
- percapinc
- mdewrk
- mdemftwrk
- mdefftwrk

Housing:
- mdvl
- mdgr

**Comment by chriswhong** [comment]
This should happen on the backend, before the data arrives in the browser.

**Comment by allthesignals** [comment]
2006-2010 estimate and moe values for above variables should be multiplied against the infltnFctr10to16 provided in metadata

**Comment by chriswhong** [comment]
Add specialCalculations for `sum` and `m` for all of these variables

**Comment by chriswhong** [comment]
Added inflation special calculation util in https://github.com/NYCPlanning/labs-factfinder-api/commit/3a9533884735319be8bd7613a1975e8b6d4c8567
