### ISSUE TITLE
Reorganize comparison area list

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#209]

**Comment by chriswhong** [comment]
- Move NYC to the top
@EricaMaurer to finish this list of changes.

**Comment by JoelAAlvarez** [comment]
[RevampedCompareToList_CityAndBoroughs.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46da918c228f93ac8bcab04eb45ce2911d490b7a3a109c087991fa09b146590e1d000bfb191b4d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae34853a7143066e273336e0a.xlsx)
[RevampedCompareToList_NTAs.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46da918c228f93ac8bcab04eb45ce2911d490b7a3a109c0544a4f06af3006b1300051bff054a5556f9f0dc23f2b43821885403b985695f74c06914a8bc821bb613a632c91edbe2e3d7158abd7f37ed998e48341f00198bfa5b36a79e48c85bf759ac.xlsx)
[RevampedCompareToList_PUMAs.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46da918c228f93ac8bcab04eb45ce2911d490b7a3a109c1b45a8c23bfd0e39111d0014f9121c4d4eeefc807eaee23e74db5e03e585395b74c63b45a9bc861fbb08a83c990dd4e8e8d51199a26867f5819d4e3914041d88fd5833a39e4cc159f348f300.xlsx)

**Comment by JoelAAlvarez** [comment]
I uploaded three tables showing the layout (re-ordered and re-labeled) for what should now be three sections in the updated "compare to" drop-down menu. It starts with a "City & Boroughs" section, then a "Neighborhood Tabulation Areas (NTAs)" section, and finally a "PUMAs (approximations of Community Districts)" section. The NTA and PUMA sections are organized alphabetically by name and are subdivided by borough -- with borough headers at the top of each sub-section. Also note the removal of all park NTAs and the airports NTA (only for this comparison list).

**Comment by chriswhong** [comment]
I've got this almost all the way working, the issue is splitting up the NTA and PUMA lists by borough and adding a sub -header to name the borough.  I think this is probably not a huge deal since the input is a typeahead search that will filter results on the fly, so it's easy to type a neighborhood name.
