### ISSUE TITLE
Complete remaining estimates and logic for special variables

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-nyc-factfinder#214]
We only have medians now, we need means and rates now.

**Comment by chriswhong** [comment]
Calculations should be handled differently if the user has a single geometry selected

**Comment by allthesignals** [comment]
- [ ] means
 - [ ] rates
 - [ ] bypass calculations when single geometry selected

**Comment by allthesignals** [comment]
This issue only includes _estimate_ logic.
