### ISSUE TITLE
Re-usable Bar Chart

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#216]
Refactor the bar chart component, add it to all sections the customer specifies

**Comment by chriswhong** [comment]
@EricaMaurer Please provide the list of sections that get a bar chart.

**Comment by EricaMaurer** [comment]
[Mockups and Charts.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46c59b99289793bacfe8b147e47ef8953b5234316546b3397f8fe62bab0021435a561ba4155a5b15fef1817ff2b23c708c080ee9d56d5b7dd42103eee9dc4be05ce36ade0d97bcae8b4bcae93824e6838f4d371b001b80fe4f78.xlsx)

**Comment by CeciliaCY** [comment]
[charts.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46eb9c9b319690ebc3abaf51ab57f5973d047d317c5da67374d7b729ed1a23050b5b4eac470c5a40f8f98d22b4aa2e32db025fb28c341521842f1bbeb98b15be04bb228b4a80b7bf8b4ac5ed2f68.zip)

Charts config file

**Comment by CeciliaCY** [comment]
[charts.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46eb9c9b319690ebc3abaf51ab57f5973d047d317c5da67374d7b729ed1a23050b5b4eac470c5a40f8f98d22b4aa2e32db025fb28c341521842f1bbeb98b15be04bb228b4a80b7b98f4dc6eb2f68.xlsx)

updated mockups and charts

**Comment by EricaMaurer** [comment]
both labels for tenure chart have been updated

[Mockups and Charts.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46c59b99289793bacfe8b147e47ef8953b5234316546b3397f8fe62bab0021435a561ba4155a5b15fef1817ff2b23c708c080ee9d56d5b7dd42103eee9dc4be05ce36ade0d97bcae8b45cae93824e58a8c473b1e031a8bfa4f78.xlsx)
