### ISSUE TITLE
Lock column headers

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#222]
When user scrolls down the page and is in the middle of a large sub-section, column headers are no visible. Would be great if column headers were locked in place

**Comment by chriswhong** [comment]
This is complicated because it requires having fixed heights for the tables.

**Comment by chriswhong** [comment]
Add sticky header and remove headers from tables.

**Comment by andycochran** [comment]
- [x] New branch `222-lock_table_header` 
- [x] Uses `ember-sticky-element` to stick tables containing only headers to the top/bottom of their `div.table-scroll`
- [x] `thead` elements have been removed from their tables and placed into a new `{{acs-table-header}}` component in a new table
- [x] Uses `ember-responsive` to conditionally wrap the `{{acs-table-header}}` component in a `{{sticky-element}}`on large screens
- [x] ember-responsive settings match Foundation's breakpoints

TODO: 
- [ ] Add a scroll listener to each `{{acs-table}}`'s `div.table-scroll` and dynamically apply `left: -x]' to the sitcky element — where `x` is the difference between the left edge of table and its non-scrolling container.

**Comment by chriswhong** [comment]
Taking a look at the TODO from above...

**Comment by andycochran** [comment]
Got the scroll/offset working. Added a couple bugs to the above list. Will tackle tomorrow.

**Comment by andycochran** [comment]
This is working pretty well. I'll PR and get this into `develop` so the customer can test it out (especially in IE). The offset bug can be handled separately in a new issue, as it's an edge case.
