### ISSUE TITLE
Data issue - Renter-occupied row returns all 0 on Housing Tenure Table (housing page)

### ISSUE THREAD

**Issue by CeciliaCY** [NYCPlanning/labs-nyc-factfinder#223]
On page - https://nyc-factfinder.planninglabs.nyc/profile/housing

Housing Tenure Table, Renter-occupied Row returns all 0.

**Comment by EricaMaurer** [comment]
Same as issue 185.. in this week's sprint 
https://github.com/NYCPlanning/labs-nyc-factfinder/issues/185
