### ISSUE TITLE
Male and female labels not appearing on pyramid chart

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#227]

**Comment by andycochran** [comment]
This is a regression. Probably result of a merge conflict. The "Male/Female" header was moved from the D3 into an HTML header. I'll hunt this down and fix…

**Comment by EricaMaurer** [comment]
This can wait until chart day

**Comment by andycochran** [comment]
The culprit: https://github.com/NYCPlanning/labs-nyc-factfinder/commit/602cb861f84871c161cc20bf509fd6618611bf5d#diff-13f48cce8aa687565aec387d9b168415L34

@chriswhong  👀
