### ISSUE TITLE
Add About Page

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#235]
Add about page with data citations, full table download links, Feedback loop, etc

**Comment by chriswhong** [comment]
Create route, add minimal information on feedback loop, data sources, etc...

**Comment by andycochran** [comment]
New branch `235-about_page` with route, header link, and basic layout. Still need: 
- [ ] email address for feedback loop
- [ ] list out data sources

**Comment by andycochran** [comment]
@EricaMaurer Does Population already have a feedback email to use for this?

**Comment by andycochran** [comment]
@chriswhong You wanna add the data info? Then we can call this done.

**Comment by chriswhong** [comment]
I'll take care of it today.
