### ISSUE TITLE
Remember last data mode selection

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#243]
When a user switches to the "change over time" data mode in a profile tab and switches to another tab the application switches back to the "current" data mode. The application should stay in the data mode the user selected when the user switches tabs.

**Comment by chriswhong** [comment]
Hotfixed in b56774b7884c7086b48535c36990207e30db6762, all tabs will now have a built-in `mode` query parameter.
