### ISSUE TITLE
Add cell tooltips in lieu of sticky headers

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#249]
Add a cell tooltip that will tell the user which column they are looking mousing over.

**Comment by CeciliaCY** [comment]
We may add row information to the tooltip too. Check this - no row info at this view:
![A26B30DC-5711-4413-A184-A38802EB811E.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46c9c6cc01d1d38daca4ea14f50cbdc07d17743e0855fb7f3da4b070e71229242d574fad344a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df749e04a51a1133562e2712431.jpeg)
