### ISSUE TITLE
Selected area is de-selected while drawing around the selected area

### ISSUE THREAD

**Issue by CeciliaCY** [NYCPlanning/labs-nyc-factfinder#250]
I select some tracts, then I use drawing tool to draw a shape around the selected tracts. Then the selected tracts are de-selected.

I think users are expecting to not de-select the area, but keep them selected.

**Comment by CeciliaCY** [comment]
![71AB8BCA-7422-4FCC-B16A-3F157D120937.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ee0299cfdf5100126377c2/125516c66e82c728ace21e0d46bfc5bb01daa18aaea4e817f60fbdc00f65043e0b55f50a3dd6c579ea155f505d5f47af464a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df749e34f5ca2153066e1732431.jpeg)

**Comment by andycochran** [comment]
This is no longer the case. Closing.
