### ISSUE TITLE
Fontawesome icons not appearing when deployed

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#253]
Radio buttons, tooltips, map icon, etc.

**Comment by allthesignals** [comment]
`ember s --environment=“production”` reproduces the error locally. Probably something with the asset pipeline.

**Comment by allthesignals** [comment]
Issue already reported here: https://github.com/martndemus/ember-font-awesome/issues/181.

There is no known cause, but setting up this in `ember-cli-build.js` solves the issue:
```javascript
    'ember-font-awesome': {
      removeUnusedIcons: false,
    ,
```
