### ISSUE TITLE
User should not see percent change over time, when earlier time (Census 2000 or ACS 2006-2010) is blank or zero

### ISSUE THREAD

**Issue by JoelAAlvarez** [NYCPlanning/labs-nyc-factfinder#261]
Since the earlier time period (Census 2000 or ACS 2006-2010 depending on your profile tab) is the denominator in change over time calculations, percent change calculations where the earlier time period is blank or zero should appear as blank.

**Comment by CeciliaCY** [comment]
Possibly solved by a branch cy-branch. Need to have a double check
