### ISSUE TITLE
Special cases where data cells should be blank

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#266]

**Comment by EricaMaurer** [comment]
Data cells should be blank for...

- Percent MOE should be blank for all section base variables
- Percent and Percent MOE should be blank for: 
  -- medians
  -- means
  -- rates
  -- CNI1864_2
  -- CvLF18t64
  -- SMPNtC
  -- NMSMPNtC
  -- GRnoRntPd

**Comment by allthesignals** [comment]
Fore example, "total population" should have no percent MOE:
![image](https://user-images.githubusercontent.com/5004319/33741543-cd645e1a-db72-11e7-8341-3f1d3c55d2f8.png)

Remove percent and percent MOE for all special variables.

**Comment by EricaMaurer** [comment]
These rules also apply to "Change Over Time"

**Comment by allthesignals** [comment]
" Percent MOE should be blank for all section base variables" @EricaMaurer 

what about comparison area percentage MOE?

**Comment by EricaMaurer** [comment]
A few instances were missed:

Comparison percent (current) should be blank: 
-- Economic--> Health Insurance: CNI1864_2
-- Economic--> Health Insurance: CvLF18t64

Comparison percent (current) and both time points in Change view should be blank:
-- Housing--> Selected Monthly Owner Costs as a Percentage of Household Income: SMPNtC
-- Housing--> Selected Monthly Owner Costs as a Percentage of Household Income: NMSMPNtC
-- Housing--> Gross Rent: GRnoRntPd

Percent and percent MOE for both selected and comparison area (current) and both time points in Change view should be blank:
-- Housing--> Gross Rent as a Percentage of Household Income: GRPINtC

**Comment by allthesignals** [comment]
@EricaMaurer will update data dictionary so that the base values for these cases will be null

**Comment by EricaMaurer** [comment]
[Data Dictionary_0610-1216 database_Feb142018.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cc958e22c2a7a08cfdb64caa5ce28d161671227949f27921d3a32cbe567a030e1c1bc3370d0d45f8fb892aaea42062ca1e54b7843e1b66cc2f14a5ed8a4bbd05eb228347d1e2b88a4cc6bc3821e38b8b462c02175ad8a1096afdc0019d1ae441f34c52ae123362ee70357a42951b722f6d756b.xlsx)

**Comment by allthesignals** [comment]
@chriswhong is using this in the new database, this will be fixed then
