### ISSUE TITLE
Change-over-time mode not working on Decennial profile

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-nyc-factfinder#272]

**Comment by allthesignals** [comment]
@andycochran I may have fixed this but can you clarify pls

**Comment by andycochran** [comment]
IDK. I closed it so must've fixed whatever issue I was documenting. Not sure why it's reopened.

**Comment by EricaMaurer** [comment]
I reopened it the other day because the view wasn't showing 2000 to 2010 data or headers

**Comment by allthesignals** [comment]
@EricaMaurer check the data - I think the headers are still the wrong dates, but the actual data should be correct, including CoT

**Comment by EricaMaurer** [comment]
Change over time view is just for the selected area... so the data that should be shown in that view are the 2000 data and 2010 data for the selected area-- not 2000 to 2010 change for each area.

**Comment by EricaMaurer** [comment]
This is fixed
