### ISSUE TITLE
Migrate SQL queries into API

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-nyc-factfinder#277]
SQL queries are long and unwieldy, and we may see multiple versions of them. It might make more sense to keep them in the API as versioned endpoints.

**Comment by allthesignals** [comment]
- Set up caching for responses so that the same reports are saved and do not hit carto again

**Comment by allthesignals** [comment]
To do : 
 - [ ] ACS Query
 - [ ] ACS Single Geom logic
 - [ ] Decennial

 - [ ] Wire up to front-end
 - [ ] Debug frontend with new API

**Comment by chriswhong** [comment]
Significance added in c4004c2 (labs-factfinder-api)
