### ISSUE TITLE
Demographics Tab - User can view or hide reliability data

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#28]
Ability to show/hide data reliability (MOE, CV, Percent MOE).

Data that is not reliable will still appear gray even when "data reliability" is switched off

**Comment by chriswhong** [comment]
The ability to infer reliability is always present using visual elements, but you can also show/hide the actual reliability numbers.

**Comment by andycochran** [comment]
There are now controls for this in `develop`.

**Comment by chriswhong** [comment]
Necessity of middle row of header labels is questionable, try removing it and design a better way to display the associated columns.

**Comment by chriswhong** [comment]
Done when toggling "RELIABILITY DATA" checkbox also toggles all MOE, CV, and Percent MOE columns
