### ISSUE TITLE
No footer

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-nyc-factfinder#280]
There isn't a footer in the report view - should there be?

**Comment by andycochran** [comment]
What type of content would you expect here? Earlier today I made a PR (#293) that'll help users know they've reached the end. But maybe more is needed. Back to top scroll-to button?

**Comment by allthesignals** [comment]
@andycochran any standard footer content would work because it serves as a visual cue that the user has reached the end of the document, and it's fairly standard web design to include a footer for scrollable documents. Our other apps are map-based with very little sense of a "document" that plays a central role, so they don't necessarily include one, however, in Community Profiles, as well as a few other products, we include a footer. [Census Reporter](https://censusreporter.org/profiles/16000US2507000-boston-ma/) includes one as well, and it parallels the structure of this app in a number of ways.

Padding is nice but the abrupt end suggests something went wrong:
![image](https://user-images.githubusercontent.com/5004319/33775156-7b307810-dc0b-11e7-82dc-5cb390cb9c06.png)
