### ISSUE TITLE
Median MOEs need to be calculated

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#281]
Didn't check for accuracy, just if the data for medians were there or not
 
 - [x] Can confirm that medians for single geogs are being calculated and not pulled from database (related to #274) 

 - [x] Percent and percent moe columns should be blank for all medians (should be handled with issue #266)

 - [x] MOEs (and as a result, also CVs) are missing for all medians

 - [x] Estimate is missing for median earnings, median earnings for males and median earnings for females
   - [x] mdewrk
   - [x] mdemftwrk
   - [x] mdefftwrk

**Comment by allthesignals** [comment]
@EricaMaurer many of the missing medians require additional variables that were not migrated into the app's database because their column names did not follow the "e"-suffix naming convention. Either I migrate that data now, only to do it again next week when the new ACS data is available, or I push this off until that data is available and I can work on it then. 

Thanks!

**Comment by allthesignals** [comment]
@EricaMaurer I know you suggested this earlier, but we should meet at some point to go over these instructions:

![image](https://user-images.githubusercontent.com/5004319/33741794-ccb37860-db73-11e7-8f70-7e300a1b9e8c.png)

Right now I have code that can:
 - do linear interpolation
 - perform a sequence of mathematical operations with a given inputs, variables, honoring PEMDAS

What I need to figure out is how much of this can be done using what I have already built, and what do I need to build out that's new for these 10 calculations.

Thanks!

**Comment by allthesignals** [comment]
Notes on this: 
1. "Weighted frequency distribution" is the bins, 'cumulative sum' is the universe calculated 
in the regular median interpolate.

2. STANDARD ERROR = DF * ((93/7*"cumulative sum") * 2500))^.5

4. Use Percentile_lower and Percentile_upper to determine the categories (bins) that they fall. 
   If Percentile_upper is 85th percentile, then you might get 65-69. This will return two bins.

5. ( this is a difficult case ) if these two bins are the same, there is some difficult
   additional logic (skip this step)

6. 
  A1: smallest value in that category
  A2: smallest value in the next higher category
  C1: cumulative percent of units strictly less than A1
  C2: cumulative percent of units strictly less than A2

  Use the formulas in step 5.
  This step produces the lower and upper bound

7. Use lower and upper bounds to calculate the standard error (formula in notes) 
    To turn this Standard Error (SE) into a Margin of Error (MOE) according to the standard Census Bureau 90% confidence interval multiply the SE by 1.645

**Comment by allthesignals** [comment]
Reopening for QA/QC from @EricaMaurer 

I'd like to have some test scenarios for this (including bins and estimates).

**Comment by allthesignals** [comment]
@EricaMaurer says this is closed!
