### ISSUE TITLE
About - add descriptions for Census, ACS data

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-nyc-factfinder#284]
PR #283 added an about page listing our data sources. There's lorem ipsum for the Census and ACS data. Please replace this with real descriptions.

**Comment by andycochran** [comment]
PR #371 adds Features and Data pages. All three pages have `TODO` comments where the text should be updated.

**Comment by EricaMaurer** [comment]
[Features_2-4-18.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46ce919b379791ac9cd6ed0ef010a1cc6b0a65633b0ba92e7391a172fd172204570b4ca8105a574ca8ad8d2ba6b068758e580be9d87f4366846c4ff8e7df46f554f832815d84b1b68b49c1ef3521e48b8b4e3619050ac4.docx)
