### ISSUE TITLE
User can identify estimates with poor statistical reliability

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#29]
Data associated with estimates of zero, top- and bottom-coded estimates, or Coefficients of Variation (CVs) of 20% or more are grayed out to signify poor statistical reliability

Applicable for standard, standard with reliability, and change over time (without reliability)

**Comment by chriswhong** [comment]
"Grayed out means it's not good for general use, you probably don't want to make a big deal of this statistic in general"

**Comment by chriswhong** [comment]
Instead of asterisks we can use specific icons (plus color codes) to emphasize certain things...

**Comment by chriswhong** [comment]
Issue is complete when 
- cells with poor statistical reliability are "grayed out"

**Comment by andycochran** [comment]
What's meant by "top- and bottom-coded estimates"?

**Comment by EricaMaurer** [comment]
Top- and bottom-coded median estimates. We will give you a list of the top- and bottom-coded values for each.

**Comment by EricaMaurer** [comment]
Top- and bottom-coded median values will not appear on the demographics tab.

**Comment by EricaMaurer** [comment]
Cells with poor statistical reliability are not grayed out

**Comment by EricaMaurer** [comment]
Top- and bottom- coded median values 
[TopAndBottomCodedVals_06-10and11-15.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46dc9b8a028c878b80fdab4ca97eff902c42117225179c7b26c8b278be4c7f505e424fa953444d04bea6d37ef5f22e7a985902b8d9395d70973f19a4ecd61bbf01bc748e4b81b6b8835edcfa7f74b9dfd0126754505a9bf54f34a8934acd59f64de64d55a5153f62e3647b.xlsx)

**Comment by allthesignals** [comment]
How are the median values related to the ability to identify poor statistical reliability?

**Comment by allthesignals** [comment]
@EricaMaurer @andycochran

**Comment by EricaMaurer** [comment]
@allthesignals the exact same rule applies to medians as to any other statistic... with the addition of top- and bottom- coded values.

For medians:
If the CV is 20% or more, all associated data would appear gray
If the MOE is blank from our database or your calculations, all associated data would appear gray

**Comment by allthesignals** [comment]
Alright, so this issue is really: 

 - User can see median estimates and summed estimates
 - User can assess reliability of all estimates

**Comment by EricaMaurer** [comment]
The statistical reliability of median estimates

**Comment by EricaMaurer** [comment]
This shouldn't be closed yet. 

This issue should be closed when the scenarios listed are grayed out to signify poor statistical reliability
- data associated with estimates of zero
- top- and bottom-coded median estimates
- Coefficients of Variation (CVs) of 20% or more

**Comment by allthesignals** [comment]
@andycochran @chriswhong is anything blocking this? IDk why this is still lingering.

**Comment by chriswhong** [comment]
We just need to do it... Let's get it on our radar tomorrow.

**Comment by chriswhong** [comment]
If the estimate is 0, it should be gray, and all data associated with that estimate should be blank.

If you are in the "median" rows, and there is a top or bottom coded median value, that value should be gray and all data associated with that estimate should be blank.

Top coded and bottom coded values should have a plus or a minus after it.

If CV >= 20, all 5 related values should be gray (see attachment)
![NYC_Population_Factfinder 2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/580f65f4e41c721300d753c7/125516c66e82c728ace21e0d46c6adb91cb28cb99ae5be57ad52feab0f4724672f0dad2f7597a37afd0e39111d0014f9121c4d4eeefc807eaee23e74db5e03e585395b74c63b45a9bc861fbb08a83c990dd4e8e8d51199a26867f5819d4e3714041d88fd5b32a59d48ca5ff74ef300.png)

**Comment by chriswhong** [comment]
#1 and #4 implemented in 11414d7ff45021b880e379772c317bde0f2b792b
