### ISSUE TITLE
Rikers colored black in below poverty and median gross rent maps

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#291]

**Comment by EricaMaurer** [comment]
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa2e2881b17cbe1023590b0b4aac415e0b41f8fd892fafa42062c80d55b98e30063e937f03a6aa8317b500bf21894881b3b98a4bc6e03f37aa.JPG)

**Comment by chriswhong** [comment]
Attempted to work on this today, but getting really spotty responses on the vector tiles that power the choropleths.  Tabling for now.
