### ISSUE TITLE
Thematic maps should mention summary level

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-nyc-factfinder#303]
It's unclear to some users how the thematic maps are summarized

**Comment by JoelAAlvarez** [comment]
Here's how we'd like the Thematic map section to appear, including tooltip links
![ThematicMapSection.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46dc9c9f2e8397a08cc4be539758f380204929316546b3397f8fe62bab0021435a561ba4155a5b15fef1817ff2b23c708c080ee9d56d5b7dd42103eee9dc4be05ce36ade0d97bcae8b45cae93824e38f8847391d041a8ffb4f78.PNG)

**Comment by EricaMaurer** [comment]
Once the summary levels are added to the thematic map section: Tooltips will need to be added to each of those summary levels. Below is the phrasing for each of the tooltips... I can add the text if there's a placeholder for each.

[TooltipsWithPhrasing_ThematicMaps.pptx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46dc9b952f968ab99cdeb657ac6df88628552e7d2e3b97237588e23cb64156001f1c5cb053181d1ba6acda6fb4bc2e75830903b9d3690e76ce3545f8bc821fb955bf248f4f81bfae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4acd58ff4de84e5da7103f71ab.pptx)
