### ISSUE TITLE
Scrolling subsections unresponsive

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-nyc-factfinder#304]
App may be entering a regressed error state preventing the scroll-downs from working. This occurred during a live demo and requires some investigation

**Comment by allthesignals** [comment]
If you enable a thematic map, choose different types, the scroll-tos stop working. The scroll to top button in the footer also stops working.

**Comment by andycochran** [comment]
I'm not certain this is related to thematic maps. I can reproduce this consistently by navigating to or directly loading a profile, then going to [map, about, etc], then back to a profile  by either clicking the "view profile" button or the back button. The scroll-to links seem to only work the first time a profile is loaded.

**Comment by chriswhong** [comment]
Added an issue at https://github.com/ragnarpeterson/ember-scroll-to/issues/39 looking for help.

**Comment by allthesignals** [comment]
I think this was fixed with a recent update of the scroll-to addon. Removing the scroller serice extension
