### ISSUE TITLE
Remove the  "comparison to" option in "change over time" views

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#310]
This applies to both ACS and Decennial.

No comparison area in "Change Over Time"

**Comment by andycochran** [comment]
@EricaMaurer This means in the "Change Over Time" mode we remove 1) the dropdown in the profile header AND 2) both Comparison Area columns AND 3) both "Difference" columns — so there'll only be 3 columns in the change tables (row name, estimate, percent estimate)?
