### ISSUE TITLE
Modify census block labels

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#313]
Remove spaces and add labeling guide

**Comment by EricaMaurer** [comment]
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa2e2881b17cbe1023590b0b4aac415e0b41f8fd892fafa42062c80d55b98e30063e937f03a6aa8317b500bf21884985beb9884ac1e83c37aa.JPG)

**Comment by JoelAAlvarez** [comment]
Add borough name to block labeling
3 Census Blocks (Tract ID-Block ID): [Bronx] 7-1000, [Brooklyn] 7-1000, [Manhattan] 7-1000

**Comment by andycochran** [comment]
Related to #365

**Comment by chriswhong** [comment]
Additional key for blocks added in f1b1700c293d75bf70f687a8dcf851880f1f8dc8, the rest was implemented in #365, closing.
