### ISSUE TITLE
Census data should not appear gray

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#315]

**Comment by EricaMaurer** [comment]
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa2e2881b17cbe1023590b0b4aac415e0b41f8fd892fafa42062c80d55b98e30063e937f03a6aa8318b500bf21884985bfb98d49c4ea3537aa.JPG)

**Comment by andycochran** [comment]
This is due to:

```js
<td class="{{unless data.percent_significant 'medium-gray'}}">{{differencePercent}}</td>
```

Instead of defaulting to **gray unless significant**, we should default to no color class and check for **_insignificance_** and apply the `medium-gray` class to only those.
