### ISSUE TITLE
Set-up Analytics

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#327]

**Comment by JoelAAlvarez** [comment]
Here's our "wish list".. I'm sure there's things we are missing. Feel free to add other items

[Analytic Wish List.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46c99a9b2f9b97a08ca9884ab755b0b8205533316546b3397f8fe62bab0021435a561ba4155a5b15fef1817ff2b23c708c080ee9d56d5b7dd42103eee9dc4be05ce36ade0d97bcae8b4bcae93824e38f864e391607188dfd4f78.docx)

**Comment by andycochran** [comment]
Turning the above Word file into a checklist we can tick off as we create these… 

- [ ] **Which geographies are being used to create profiles?**
_Can we get this data from the existing profiles in the API? Should Google Analytics log every geography that is selected when the profile is created? Should we log each geography click (seems overkill)?_
- [ ] **How many profiles are individual geographies vs aggregate?**
- [ ] **User interacted with draw tool** 
  - Category: Draw
  - Action(s): draw start, draw cancel, draw complete
  - Label(s): [started, stopped, completed] [geogType] drawing
  - Value: number of geographies contained within shape _(for completed)_
- [ ] **User interacted with search**
  - Category: Search
  - Action(s): focus, blur, received results, no results
  - Label(s): `null`, `null`, terms, terms
- [ ] **User interacted with Advanced Options**
  - Category: Advanced Options
  - Action(s): open adv options, close adv options, [on, off] layer group, chose choropleth
  - Label(s): `null`, `null`, layer group name, layer group name, choropleth name
- [ ] **Behavior Flow: How many times (average, min, max, median) does the user go between the map and profile views?**
_We'll get this without any custom events, just by tracking route change_
- [ ] **How users navigate profiles**
  - Category: Profile Navigation
  - Action(s): went back to map, changed profile tab, opened tab dropdown, scroll to section
  - Label(s): clicked [static map,  map icon], tab name, tab name, section name
_Can we also track back button as an event for returning to map?_ 
- [ ] **User adjusted the view of the profile**
  - Category: Profile Settings
  - Action(s): turn reliability on, turn reliability off, choose comparison area, switch mode, turn charts on, turn charts off
  - Label(s): `null`, `null`, comparison area name, [current, change] mode, `null`, `null`
- [ ] **User gets data**
  - Category: Data
  - Action(s): copy to clipboard, downloads csv
  - Label(s): table name, `null`
- [ ] **User goes to About page**
_We'll get this without any custom events, just by tracking route change_

**Comment by andycochran** [comment]
@allthesignals I'd love to pair with you on this.

**Comment by andycochran** [comment]
New branch: `327-analytics`
