### ISSUE TITLE
Differences and changes over time should appear blank when median is top- or bottom-coded

### ISSUE THREAD

**Issue by JoelAAlvarez** [NYCPlanning/labs-nyc-factfinder#339]
In current view (2012-2016):
when one or both of the medians being compared (selected or comparison area) is top- or bottom-coded, then resultant difference and MOE of difference (both numeric and percentage point) should be blank

In change over time view (2006-2010 to 2012-2016):
when one or both of the medians being compared (2006-2010 to 2012-2016) is top- or bottom-coded, then resultant estimate of change and MOE of change (both numeric and percent) should be blank

**Comment by andycochran** [comment]
Once we've top- and bottom-coded medians, let's make sure this works as expected.

**Comment by allthesignals** [comment]
This is working for multi-geography aggregates but not for single geographies because the server does not apply special calculations to single-geographies because those are provided up-front.

**Comment by EricaMaurer** [comment]
Closing this. Keep the + sign for multi-geog and ok to leave it off for single geogs. We will add a note in the tool tips to let users know about the top- and bottom- coded values.
