### ISSUE TITLE
User can select and deselect tracts or blocks in an ad-hoc manner

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#34]
Select button should be easier to use than in current application.

Always active. Just need to click on geography.
Can scroll around map without having to turn select button off.

**Comment by chriswhong** [comment]
- [ ] Click Tract or Block to toggle selection
- [ ] Create

**Comment by chriswhong** [comment]
Labeling advice:

Tracts should simply use  the `ctlabel` column.
Blocks will use a hybrid label: {census tract label} - {cb2010}
