### ISSUE TITLE
NTA aggregation not appearing in Census tab

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#345]
https://nyc-factfinder.planninglabs.nyc/profile/333/census

**Comment by allthesignals** [comment]
Error is: `"invalid input syntax for integer: "MN22"`

This is likely related to the migration. The geoid was probably converted to integer thanks to Carto's type-guessing.

**Comment by allthesignals** [comment]
`decennial_sex_age` table has this issue - geoid is converted to a Carto "number" type. The table needs to be re-uploaded and replaced, with type-guessing disabled.

**Comment by allthesignals** [comment]
This has been fixed
