### ISSUE TITLE
Percents for some age groups missing

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#347]

**Comment by allthesignals** [comment]
@EricaMaurer I discovered that many of those age by population values are not unique and conflict with the special variable names. While variable names should not be unique across year, they should be unique across all categories.

**Comment by allthesignals** [comment]
This will be fixed in the next data release.

**Comment by allthesignals** [comment]
New data and data dictionary in hand, need to melt and upload.

**Comment by allthesignals** [comment]
@EricaMaurer Some of the Variable Names in the data dictionary still include the E suffix, while others do not... specifically, the special variables. I can't move forward until that's fixed - thanks!

**Comment by EricaMaurer** [comment]
[Data Dictionary_0610-1216 database.xlsx](https://github.com/NYCPlanning/labs-nyc-factfinder/files/1583569/Data.Dictionary_0610-1216.database.xlsx)
