### ISSUE TITLE
Add missing data in tables

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-nyc-factfinder#353]
Once #352 is merged, there are placeholders in the new cells that need dynamic data. 

- ACS/Current: 
    - [ ] Diff>Num>MOE 
    - [ ] Diff>Pctg.Pt.>MOE 
- ACS/Change: 
    - [ ] 2006-2010>Num>MOE
    - [ ] 2006-2010>Num>CV
    - [ ] 2006-2010>Percent>MOE
    - [ ] 2012-2016>Num>MOE
    - [ ] 2012-2016>Num>CV
    - [ ] 2012-2016>Percent>MOE
    - [ ] Change, 2006-2010 to 2012-2016>Pctg. Pt.>MOE

**Comment by EricaMaurer** [comment]
Change, 2006-2010 to 2012-2016>Pctg. Pt.>MOE= SQRT((POWER(2006-2010 percent MOE)/1.645),2))+(POWER(((2012-2016 percent MOE))/1.645),2))))
