### ISSUE TITLE
2006-2010 medians

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#360]
All medians, except for median value (issue #355) and median gross rent (issue #356) have the same bins as 2012-2016 medians

**Comment by allthesignals** [comment]
Need logic for switching between sets of bins for respective year ranges

**Comment by allthesignals** [comment]
Okay, so median gross rent and median value need different bins? @EricaMaurer

**Comment by allthesignals** [comment]
Closing this because there's no issue here - only the issues linked above
