### ISSUE TITLE
Style charts

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#364]

**Comment by andycochran** [comment]
Instead of truncating, consider wrapping labels to multiple lines (since we've increased the height of the bars). 

<img src="https://user-images.githubusercontent.com/409279/34579265-461ff546-f156-11e7-8cd1-2b37189ef1c8.png" width=400 />

**Comment by andycochran** [comment]
New `364-style_charts` branch has these changes. 

@chriswhong: 
- We may need to pair on the ~truncating~ line wrapping. And preventing extending past 100%. 

@EricaMaurer: 
- What are the titles you'd like to use for each chart? Let's avoid repeating the header above the table.
- And which charts would you like to add to Census? Need to add those to `/app/chart-config/census/`.
