### ISSUE TITLE
User should see geography name at top of all profiles

### ISSUE THREAD

**Issue by JoelAAlvarez** [NYCPlanning/labs-nyc-factfinder#365]
User should see geography name/label and borough for all profiles -- sometimes in addition to geography IDs (See case-by-case descriptions below)

Census Block view: see comment in issue #313
3 Census Blocks (Tract ID-Block ID): [Bronx] 7-1000, [Brooklyn] 7-1000, [Manhattan] 7-1000

Census Tract view: Add in borough name in brackets
3 Census Tracts: [Bronx] 7, [Brooklyn] 7, [Manhattan] 7
![CensusTract.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46cb91943097909d9de8bc57e611b2843b492d762a10e17132d0ba2de74629550e5d46a4150c5b44fcffdd2ea2b23c74834e17ff933c0120996048e6edc00db513bb28814e80b7b88e4bc4ee3c24e78b8b5d73.PNG)

Neighborhood Tabulation Area view: Use labeling as it appears in issue #209 (NTA comparison list) and add in borough names
3 Neighborhoods: [Brooklyn] Greenpoint – BK76, [Manhattan] Chinatown – MN27, [Queens] Astoria – QN70

PUMA view: Use labeling as it appears in issue #209 (PUMA comparison list) and add in borough names
 [Brooklyn] Bushwick – 4002 (approx. Brooklyn CD 4), [Manhattan] East Harlem – 3804 (approx. Manhattan CD 11), [Queens] Astoria & Long Island City – 4101 (approx. Queens CD 1)

**Comment by chriswhong** [comment]
@JoelAAlvarez @EricaMaurer Why do we need brackets around the Borough Names?  What does that add besides two extra characters?
