### ISSUE TITLE
Notes for blank sub-sections in ACS "change over time"

### ISSUE THREAD

**Issue by JoelAAlvarez** [NYCPlanning/labs-nyc-factfinder#367]

**Comment by JoelAAlvarez** [comment]
Note will be "Data not comparable or unavailable"

**Comment by chriswhong** [comment]
@EricaMaurer to identify specific tables for this to apply to, we will determine if we can apply logic easily to do this, or whether it can only be done if the entire table is blank.

**Comment by EricaMaurer** [comment]
[ACS Change Over Time_blank tables.pptx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46c9b7a963a18ba881eeba038b4bf58669722e7e2c3ba127718be868ab43790d0a1c5cb053181d1ba6acda6fb4bc2e75830903b9d3690e76ce3545f8bc821fb955bf248f4f81bfae965e82b96371b8d6d6056b5c17129bfe543fa19c4acc51f44de34f57a5153771ab.pptx)
