### ISSUE TITLE
Census "special variables" need to be calculated

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#376]
- population per acre
  = pop1/landacres

- average household size
  = popinhh/hh1

- average family size
  = popinfam/fam1

- homeowner vacancy rate
  = (vhufslo/(vhufslo+oochu1))*100

- rental vacancy rate
  = (vhufrnt/(vhufrnt+rochu_3))*100

- average household size of owner-occupied units
  = popoochu/oochu

- average household size of renter-occupied units
  = poprochu/rochu_1

**Comment by allthesignals** [comment]
This should be possible through the decennial config

**Comment by allthesignals** [comment]
We'd use the calculator utility

**Comment by EricaMaurer** [comment]
@allthesignals 

population per acre
= (GET("pop1.sum"))/(GET("landacres.sum"))

average household size
= (GET("popinhh.sum"))/(GET("hh.sum"))

average family size
= (GET("popinfam.sum"))/(GET("fam.sum"))

homeowner vacancy rate
= ((GET("vhufsio.sum"))/((GET("vhufsio.sum"))+(GET("oochu.sum"))))*100

rental vacancy rate
= ((GET("vhufrnt.sum"))/((GET("vhufrnt.sum"))+(GET("rochu_1.sum"))))*100

average household size of owner-occupied units
= (GET("popoochu.sum"))/(GET("oochu.sum"))

average household size of renter-occupied units
= (GET("poprochu.sum"))/(GET("rochu_1.sum"))

**Comment by allthesignals** [comment]
Please update the category column decennial data dictionary for these four variables:

PopInFam
PopOOcHU
PopROcHU
LandAcres

Now, their categories are incorrect (for example, "PopInFam"'s category is `For Average Family Size`).

Their categories should be the name of the category they belong in. 

Screenshots:
![image](https://user-images.githubusercontent.com/5004319/34628812-c5b4b4c6-f233-11e7-9bc9-acb0005718bc.png)
![image](https://user-images.githubusercontent.com/5004319/34628817-c74fd6b2-f233-11e7-9ce8-b975cf8e70db.png)

**Comment by allthesignals** [comment]
2. Duplicate column when that column is needed for special calculations in a given section. 

For example, `HH` needs to be included in `relationship to head of household` for it to be used in the special variable calculations (we need to store all the categories as separate tables due to the size of Census).

**Comment by allthesignals** [comment]
@EricaMaurer here's the branch you'll need to work off of (click app -> table-config -> decennial) https://github.com/NYCPlanning/labs-nyc-factfinder/tree/376-census-special-variables

**Comment by allthesignals** [comment]
[PFF_2000to2010DataDictionary-1-06-18.xlsx](https://github.com/NYCPlanning/labs-nyc-factfinder/files/1609175/PFF_2000to2010DataDictionary-1-06-18.xlsx)
