### ISSUE TITLE
ACS MOE and CVs for means & rates need to be calculated

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#377]
- average household size
  (avghhsz)
  MOE: ((avghhszC/100)*1.645)*avghhszE
  CV: 62(uwhusmpl1)^-.503

- average family size
  (avgfmsz)
  MOE: ((avgfmszC/100)*1.645)*avgfmszE
  CV: 51(uwhusmpl1)^-.473  

- mean travel time to work
  (mntrvtm)
  MOE: ((mntrvtmC/100)*1.645)*mntrvtmE
  CV: 316(uwpopsmpl)^-.679  

- mean household income
  (mnhhinc)
  MOE: ((mnhhincC/100)*1.645)*mnhhincE
  CV: 462(uwhusmpl2)^-.754

- per capita income
  (percapinc)
  MOE: ((percapincC/100)*1.645)*percapincE
  CV: 1122(uwpopsmpl)^-.778

- average household size of owner-occupied unit
  (avghhsooc)
  MOE: ((avghhsoocC/100)*1.645)*avghhsoocE
  CV: 564(uwhusmpl3)^-.762

- average household size of renter-occupied unit
  (avghhsroc)
  MOE: ((avghhsrocC/100)*1.645)*avghhsrocE
  CV: 257(uwhusmpl3)^-.699

- homeowner vacancy rate
  (hovacrt)
  MOE: IF(((vacsaleM^2)-((vacsaleE^2/hovacuE^2)*(hovacuM^2)))<0,((1/hovacuE*(SQRT((vacsaleM^2)+((vacsaleE^2/hovacuE^2)*(hovacuM^2)))))*100),((1/hovacuE*(SQRT((vacsaleM^2)-((vacsaleE^2/hovacuE^2)*(hovacuM^2)))))*100))
  CV: same as regular CV formula

- rental vacancy rate
  (rntvacrt)
  MOE: =IF(((vacrntM^2)-((vacrntE^2/rntvacuE^2)*(rntvacuM^2)))<0,((1/rntvacuE*(SQRT((vacrntM^2)+((vacrntE^2/rntvacuE^2)*(rntvacuM^2)))))*100),((1/rntvacuE*(SQRT((vacrntM^2)-((vacrntE^2/rntvacuE^2)*(rntvacuM^2)))))*100))
  CV: same as regular CV formula

**Comment by allthesignals** [comment]
@EricaMaurer if you can double-check that these are valid formulas (syntactically), we'll be in good shape. I'm using something that parses excel formulas on the fly, in-app...

**Comment by allthesignals** [comment]
@EricaMaurer there are some slight formatting requirements with this new config system:
1. Always need explicit multiplication (*) - can't have `(10)(10) = 100`, must be `(10) * (10) = 100` or `(10) * 10 = 100`
2. in order to reference a variable, we need to replace all variable references in your formulas with a special function. So, `(vacrntM^2)` would become `(GET("vacrnt.m")^2)`. 

You'll notice in 2 that the variable name is different - it should be the non-suffix variable name plus the letter. Only exception is that `E` should be `sum`. So `(vacrntE^2)` would become `GET("vacrnt.sum")`. 

If you have time to update these, then I can plop them right in. I would propose this workflow:
 - check that formulas are valid in excel
 - replace formatting with requirement in 1
 - finally, replace variable references with formatting in 2.

Let me know if you have any questions. I'll troubleshoot the rest. Thank you!!!

**Comment by EricaMaurer** [comment]
@allthesignals let me know if anything needs to be changed!

average household size
MOE: =((((GET("avghhsz.cv"))/(100))*(1.645))*(GET("avghhsz.sum")))
CV: =(62)*((GET("uwhusmpl1.sum"))^-.503)

average family size
MOE: =((((GET("avgfmsz.cv"))/(100))*(1.645))*(GET("avgfmsz.sum")))
CV: =(51)*((GET("uwhusmpl1.sum"))^-.473)

mean travel time to work
MOE: =((((GET("mntrvtm.cv"))/(100))*(1.645))*(GET("mntrvtm.sum")))
CV: =(316)*((GET("uwpopsmpl.sum"))^-.679)

mean household income
MOE: =((((GET(“mnhhinc.cv”))/(100))*(1.645))*(GET(“mnhhinc.sum”)))
CV: =(462)*((GET(“uwhusmpl2.sum”))^-.754)

per capita income
MOE: =((((GET(“percapinc.cv”))/(100))*(1.645))*(GET(“percapinc.sum”)))
CV: =(1122)*((GET(“uwpopsmpl.sum”))^-.778)

average household size of owner-occupied unit
MOE: =((((GET(“avghhsooc.cv”))/(100))*1.645))*(GET(“avghhsooc.sum”)))
CV: =(564)*((GET(“uwhusmpl3.sum”))^-.762)

average household size of renter-occupied unit
MOE: =((((GET(“avghhsroc.cv”))/(100))*1.645))*(GET(“avghhsroc.sum”)))
CV: =(257)*((GET(“uwhusmpl3.sum”))^-.699)

homeowner vacancy rate
MOE =IF((((GET(“vacsale.m”)^2))-(((GET(“vacsale.sum”)^2)/(GET(”hovacu.sum”)^2))*( (GET(“hovacu.m”)^2))))<0,
(((1/((GET(“hovacu.sum”)))*(SQRT((GET(“vacsale.m”)^2)+(((GET(“vacsale.sum”)^2)/(GET(“ hovacu.sum”)^2))*(GET(“hovacu.m”)^2)))))*(100)),
(((1/((GET(“hovacu.sum”)))*(SQRT((GET(“vacsale.m”)^2)-(((GET(“vacsale.sum”)^2)/(GET(“ hovacu.sum”)^2))*(GET(“hovacu.m”)^2)))))*(100)))
CV: regular CV formula = ((m/1.645)/sum)*(100)

rental vacancy rate
MOE =IF((((GET(“vacrnt.m”)^2))-(((GET(“vacrnt.sum”)^2)/(GET(”rntvacu.sum”)^2))*( (GET(“rntvacu.m”)^2))))<0,
(((1/((GET(“rntvacu.sum”)))*(SQRT((GET(“vacrnt.m”)^2)+(((GET(“vacrnt.sum”)^2)/(GET(“rntvacu.sum”)^2))*(GET(“rntvacu.m”)^2)))))*(100)),
(((1/((GET(“rntvacu.sum”)))*(SQRT((GET(“vacrnt.m”)^2)-(((GET(“vacrnt.sum”)^2)/(GET(“rntvacu.sum”)^2))*(GET(“rntvacu.m”)^2)))))*(100)))
CV: regular CV formula = ((m/1.645)/sum)*(100)
