### ISSUE TITLE
Add mailchimp signup

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#378]

**Comment by EricaMaurer** [comment]
Provide your email address for future updates

**Comment by andycochran** [comment]
Have you already created the MailChimp list? I can add this to the About(?) page. Just provide the embed code for the form.

**Comment by EricaMaurer** [comment]
I made an account-- just have to figure out how to make the form.

**Comment by EricaMaurer** [comment]
Think I did it?


<link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://nyc.us17.list-manage.com/subscribe/post?u=a776404dc64249afedbd7e0df&amp;id=d47dc9a986" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">Subscribe for future updates</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_a776404dc64249afedbd7e0df_d47dc9a986" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
