### ISSUE TITLE
User can identify estimates of change and estimates of differences that are statistically significant

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#4]
By view:

- Standard (without reliability): significance labels appear to right of numeric difference and percentage point difference
- Standard (with reliability): not applicable
- Change over time (without reliability): significance labels appear to right of numeric difference and percentage point difference
- Change over time (with reliability): significance labels appear to right of numeric and percent change estimates
- Comparison change over time (without reliability): significance labels appear to right of numeric difference and percentage point difference
- Comparison change over time (with reliability): significance labels appear to right of numeric difference and percentage point difference estimates

**Comment by chriswhong** [comment]
"This comparison is a big deal... this one specific comparison is a big deal as opposed to general comparisons"

**Comment by chriswhong** [comment]
Instead of asterisks we can use specific icons (plus color codes) to emphasize certain things...  

Explore the use of icons with tooltips, so user does not have to refer to a key somewhere else in the page.

This issue is closed when:
- change over time
- difference

**Comment by andycochran** [comment]
> `=IF(ABS((SQRT((POWER(((selectedareaMOE)/1.645),2))+(POWER(((comparisonareaMOE)/1.645),2))))*1.645)>(ABS((comparisonareaestimate-selectedareaestimate))),"", "significant")`

**Comment by JoelAAlvarez** [comment]
When comparing two ACS estimates of zero, the difference will always be grayed out along with the associated MOE. The same is true for change over time -- when an estimate from 2006-2010 is zero and the corresponding estimate from 2012-2016 is also zero, the estimate of change, the percent estimate of change, and both associated MOEs should be grayed out.
