### ISSUE TITLE
Percents and percent moes are not appearing for a few variables in the 'Income & Benefits' section

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#419]

**Comment by EricaMaurer** [comment]
![Picture1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46d89d99379791acdeabf301b44fff9e2c4533317346f67275dde77aeb432959570b1aa841585910f9fd8d2ba2bf2e6c981e5ab38532022d8c6853beb2901eb70bbb258a4a80b6b48845c7ee3f20f5c6.jpg)

**Comment by andycochran** [comment]
@EricaMaurer gave us a new file for ACS dataset, which should resolve this.

**Comment by allthesignals** [comment]
![Screen Shot 2018-02-11 at 12.16.37 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455f26b7191a379ed0c2a57415c49bc21254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae94e53ad173761e77f366e0a.png)
![Screen Shot 2018-02-11 at 12.16.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455f26b7191a379ed0c2a57415d49bc21254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae94e53ad17376be5713f6e0a.png)

These are appearing now with the new data (not deployed yet)

**Comment by allthesignals** [comment]
This is working now with the new metadata once NYCPlanning/labs-factfinder-api#13 is merged
