### ISSUE TITLE
User should be able to search for known geometries

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#42]
Create microservice API for search typeahead, return results for PUMA & NTA

**Comment by andycochran** [comment]
Note: While working on the 4 selector types (block, tract, NTA, PUMA), it became evident that it could be a problem to return search results for a different selector than is currently being used. For example, if I've selected a few PUMAs and search for a neighborhood, how can I add that to my selection? Do I switch modes?

**Comment by chriswhong** [comment]
Anything that can be exploded or imploded into the current selection type should still work.  Easy fix is only those things that match the selection mode you are in will return results.  Harder: return anything that can be exploded/imploded and return it.

**Comment by chriswhong** [comment]
[https://github.com/nycplanning/labs-factfinder-api](https://github.com/nycplanning/labs-factfinder-api) exists!

**Comment by chriswhong** [comment]
Some thinking on search:  Search results should not alter the user's selection.  Rather, search is useful for orienting the map and identifying features.  In this way, a user can be in any selection mode and still see results for other selection modes on the map without altering their selection.

Example use case: I am selecting tracts and want to see the boundary for an NTA.  I search for the NTA, the boundary is overlaid on the tract selection map, and I can use that boundary as a reference for continuing to select tracts

**Comment by chriswhong** [comment]
Closed by #175
