### ISSUE TITLE
Logic from issue #344 should also be applied to 'pctg pt moe' diff and change

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#426]
-- Apply this logic to 'pctg pt moe' difference and change
Check that this is working for Number and Percent also

From #344: 

"For difference and change over time calculations, treat blank MOEs associated with estimates of zero as zero

In current view (2012-2016):
when one numeric estimate (selected or comparison area) is zero, and associated MOE is blank, treat MOE as zero for purposes of calculating MOE of numeric difference.

In change over time view (2006-2010 to 2012-2016):
when one numeric estimate (2006-2010 or 2012-2016) is zero, and associated MOE is blank, treat MOE as zero for purposes of calculating MOE of numeric change over time and percent change over time."

**Comment by allthesignals** [comment]
![image](https://user-images.githubusercontent.com/5004319/36054022-35d24058-0dc2-11e8-9731-4ce0741bfeb4.png)
If either moe is null, the difference MOE should use zero for that null value.

**Comment by allthesignals** [comment]
https://nyc-factfinder.planninglabs.nyc/profile/607/social?mode=change

**Comment by allthesignals** [comment]
Change MOE is coming back "null" from the server in these cases.

**Comment by allthesignals** [comment]
PR'd @andycochran or @chriswhong plz review thx
