### ISSUE TITLE
User should not see 2012-2016 data in change over time, when 2006-2010 data is not available

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#427]
This was ok-- but reverted back at some point

Cells should appear blank for 2006-2010 AND 2012-2016, when 2006-2010 data is not available or comparable

Could also apply #367-- notes for blank sub-sections

**Comment by andycochran** [comment]
If a row has no '06-'10 data, the rest of the row should be blank.
