### ISSUE TITLE
Data for New Zealander not appearing in Ancestry sub-section

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#428]
variable label (Nzealnder) matches in database, data dictionary, and code

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/35987797-b4c19fec-0cca-11e8-951b-4cd5d5033056.png)

**Comment by EricaMaurer** [comment]
FOUND THE NEW ZEALANDERS!!
