### ISSUE TITLE
Housing tenure- renter-occupied housing units: percent and percent MOE not appearing in application for single geogs

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#431]
Renter-occupied: rochu1

**Comment by allthesignals** [comment]
@EricaMaurer I think this may be data-related - there is no data for pct and pct moe:
[rochu_ctincl33_housing.csv.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46fa9b992b97bcaa9be0b140a80ea3ab21493260200aa4657396f56af3006b1300051bff054a5556f9f0dc23f2b43821885403b985695f74c06914a8bc821bb613a632c91edbe2e3d7158abd7f37ed998d4d341f001981fc5d30a5904bca5ff759ac.zip)

**Comment by allthesignals** [comment]
@EricaMaurer pls confirm there are percent values for these

**Comment by EricaMaurer** [comment]
@allthesignals there's values. the data label is incorrect. will fix this

**Comment by EricaMaurer** [comment]
Fixed with data update!
