### ISSUE TITLE
If percent = 100, then percent MOE should be blank

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#433]
Percent MOE should be blank but `NaN` or `0` is appearing. 

Examples: https://nyc-factfinder.planninglabs.nyc/profile/503/social
https://nyc-factfinder.planninglabs.nyc/profile/507/demographic?comparator=BK21
https://nyc-factfinder.planninglabs.nyc/profile/396/social?mode=change

**Comment by allthesignals** [comment]
![Screen Shot 2018-02-09 at 6.02.08 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454fa6b7191a37ef112294f5f575ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19041c95df743e34c52a7163460e4732431.png)
Fixed ^

Closed by da73cc76cd140884a0c349be2bf0e0533edb7088
