### ISSUE TITLE
When both estimates are 0, difference/change est&MOE will be grayed

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#435]
When comparing two ACS estimates of zero, the difference will always be grayed out along with the associated MOE. 

The same is true for change over time -- when an estimate from 2006-2010 is zero and the corresponding estimate from 2012-2016 is also zero, the estimate of change, the percent estimate of change, and both associated MOEs should be grayed out.

Example: https://nyc-factfinder.planninglabs.nyc/profile/503/demographic?comparator=BX09

**Comment by andycochran** [comment]
This is working for change over time mode, but not for current mode.

**Comment by andycochran** [comment]
Current: 
![image](https://user-images.githubusercontent.com/409279/35987092-d6e2b0ea-0cc8-11e8-8efb-a9e29bc55bef.png)

Change: 
![image](https://user-images.githubusercontent.com/409279/35987117-e7f8a150-0cc8-11e8-9c96-71f4b165cd33.png)

**Comment by allthesignals** [comment]
Closed by da73cc76cd140884a0c349be2bf0e0533edb7088
