### ISSUE TITLE
Difference est & MOE should gray out together

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#436]
Number est&moe columns should gray out together and Pctg.pt est&moe should gray out together.. but separate from each other

Currently, number est&moe are not gray at all.. and pctg pt number is gray but moe is not

**Comment by andycochran** [comment]
If the "Estimate" or "MOE" in either the "Number" or "Pctg. Pt." column, both values should be grayed out. It is currently just graying one value. 

![image](https://user-images.githubusercontent.com/409279/35986114-3065dfa0-0cc6-11e8-996e-38f66c734aa2.png)

**Comment by allthesignals** [comment]
Closed by da73cc76cd140884a0c349be2bf0e0533edb7088
