### ISSUE TITLE
If estimate is 0, MOE should be treated as a 0 in significance formula

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#441]

**Comment by andycochran** [comment]
Can't replicate. Closing for now. Please reopen if you can provide a link to an example of this bug.

**Comment by EricaMaurer** [comment]
https://nyc-factfinder.planninglabs.nyc/profile/691/social?reliability=true

Other South Eastern Asia

**Comment by chriswhong** [comment]
Closed by https://github.com/NYCPlanning/labs-factfinder-api/pull/27
