### ISSUE TITLE
Pctg pt MOE not appearing for  Ancestry sub-section

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#443]

**Comment by andycochran** [comment]
In current mode, the Difference > Pctg. Pt > MOE should have values. 

![image](https://user-images.githubusercontent.com/409279/35987545-fd568dc2-0cc9-11e8-9d29-17574e2d1fa2.png)

May depend on fixing the `NaN`s.
