### ISSUE TITLE
Possible rounding issue when calculating pctg pt difference

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#445]
https://nyc-factfinder.planninglabs.nyc/profile/493/demographic?comparator=2

Example: 5 to 9 year olds
Selected area percent showing as 3.2%
Comparison area percent showing as 7.0%
Percentage point difference showing as -3.9.. should be -3.8-- this is happening throughout the four profile tabs

**Comment by andycochran** [comment]
@EricaMaurer and @chriswhong discussed this. It might work itself out with the latest changes, moving the queries to the API.

**Comment by allthesignals** [comment]
Closed by #510 PR

**Comment by trbmcginnis** [comment]
Closed by #510 PR
