### ISSUE TITLE
Percents missing for some languages  for single geog (both selected and comparison areas)

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#446]
https://nyc-factfinder.planninglabs.nyc/profile/507/social?comparator=BK21

**Comment by EricaMaurer** [comment]
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa2e2881b17cbe1023590b0b4aac415e0b41f8fd892fafa42062c80d55b98e30063e937f03a6aa8318b500bf218d4d84beb88c4ac4ec3d37aa.JPG)

**Comment by EricaMaurer** [comment]
@allthesignals language spoken at home in the social profile

**Comment by allthesignals** [comment]
Found and confirmed:
![Screen Shot 2018-02-10 at 6.53.10 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455f36b7191a37ef117284f5e5f5ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df743e24d53ac133661e67f2431.png)

The values in the database are null:
![Screen Shot 2018-02-10 at 7.04.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455f36b7191a37ff1122f4f5f585ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df743e24d52a014366ae2722431.png)

**Comment by allthesignals** [comment]
Maybe this and #431 will be fixed by the data updates

**Comment by allthesignals** [comment]
@EricaMaurer I haven't loaded in the new data but can you please check that your new data versions include percent values for lgscdlep2?

**Comment by allthesignals** [comment]
@EricaMaurer pls take a look when you get a chance thanks!

**Comment by allthesignals** [comment]
I think this is closed when NYCPlanning/labs-nyc-factfinder#13

**Comment by allthesignals** [comment]
![Screen Shot 2018-02-13 at 3.43.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455f06b7191a37bf116284f5e5e5ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19141c95df743e44851a213316be57e2431.png)

Some of these looked wrong, let's verify @EricaMaurer
