### ISSUE TITLE
Remove percent change for select special variables (percentage point change is not calculated for any special variable)

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#448]
Demographic
- median age

Social
- average household size
- average family size

Housing
- homeowner vacancy rate
- rental vacancy rate
- median rooms
- average household size of owner-occupied housing units
- average household size of renter-occupied housing units

**Comment by JoelAAlvarez** [comment]
Census
a.	Population per acre
b.	Median age (years)
c.	Average household size
d.	Average family size
e.	Homeowner vacancy rate (percent)
f.	Rental vacancy rate (percent)
g.	Average household size of owner-occupied units
h.	Average household size of renter-occupied units

**Comment by andycochran** [comment]
These are not good comparisons for the user. We should just have blank cells for these variables.

**Comment by allthesignals** [comment]
@EricaMaurer this is specific to change over time view or is it also current view?

**Comment by allthesignals** [comment]
PR'd - @andycochran or @chriswhong  pls review thx

**Comment by EricaMaurer** [comment]
percent change is just in change over time view.. but percentage point will be blank in both views because there are no percents to calculate percentage point change

**Comment by allthesignals** [comment]
@EricaMaurer what?
