### ISSUE TITLE
Format difference-number-moe as a number with hundreds comma and zero decimals

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#449]

**Comment by andycochran** [comment]
The MOE column should be formatted to match the Estimate column. 

![image](https://user-images.githubusercontent.com/409279/35986366-dcee0c2a-0cc6-11e8-9c78-dd7d47e7cd1b.png)

**Comment by allthesignals** [comment]
Closed by  da73cc76cd140884a0c349be2bf0e0533edb7088
