### ISSUE TITLE
Update Median Rooms calculation to use .5 intervals

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#453]
Census bureau uses .5 intervals for median calculation. We should update the intervals in the median calculation

**Comment by JoelAAlvarez** [comment]
@mgardner Following-up on what Erica discussed with you regarding bins for median rooms...In computing median rooms, the whole number is used as the midpoint of the interval; thus, the category “3 rooms” is treated as an interval ranging from 2.5 to 3.499 rooms. (See attached table with all of the bin intervals.)
[BinsIntervalsForMedianRooms.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dd8bd0aa9cc0001458777b/125516c66e82c728ace21e0d46ca9d9430ab8dbd8afba942a84ed69b3b6b22772005ad197f8aee3bfd0e39111d0014f9121c4d4eeefc807eaee23e74db5e03e585395b74c63b45a9bc861fbb08a83c990dd4e8e8d51199a26867f5819d4e3914041d88f75c3ca99f4dc858f149f300.xlsx)

**Comment by EricaMaurer** [comment]
@JoelAAlvarez you closed this issue??

**Comment by chriswhong** [comment]
Implemented in 9fc7c0cae077a8e7893ddaa4a35d1e009da597cb
