### ISSUE TITLE
Comparison area MOE and CV are missing for Total Population in Ancestry for NYC and boros

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#454]
Example: https://nyc-factfinder.planninglabs.nyc/profile/493/social

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/35987720-84c046fe-0cca-11e8-9db1-d8df57e2b58d.png)

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/35987720-84c046fe-0cca-11e8-9db1-d8df57e2b58d.png)

**Comment by EricaMaurer** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/32674674/36211392-212fcb9c-116f-11e8-88a3-001ebf516dad.png)
