### ISSUE TITLE
Percent MOE appearing as NaN for Ancestry sub-section for NYC and Boros

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#455]

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/35987674-604a2f1a-0cca-11e8-8b3d-b862e9c28ec1.png)

**Comment by EricaMaurer** [comment]
Fixed
![image](https://user-images.githubusercontent.com/32674674/36211244-b580dabc-116e-11e8-8626-a3b1f2a1aa4e.png)
