### ISSUE TITLE
Homeowner vacancy rate of 0, moe and cv should be blank

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#457]
homeowner vacancy rate is 0 for 2012-2016, moe and cv should appear blank. This is ok in current view, but needs to be fixed in change over time

Example: https://nyc-factfinder.planninglabs.nyc/profile/493/housing?mode=change

**Comment by andycochran** [comment]
`#DIV/0!` 🤔

![image](https://user-images.githubusercontent.com/409279/35988163-b5ca923a-0ccb-11e8-97b9-f243f627e443.png)

**Comment by allthesignals** [comment]
![Screen Shot 2018-02-09 at 6.04.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454fa6b7191a37ef1122f4f5f585ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19041c95df743e34c52a0163564ee742431.png)

Fixed at this point here ^ and around commit da73cc76cd140884a0c349be2bf0e0533edb7088
