### ISSUE TITLE
When change-number is 0, change-moe should be 0

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#460]
Example: https://nyc-factfinder.planninglabs.nyc/profile/503/social?mode=change place of birth

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/35986703-ca603064-0cc7-11e8-9212-bf22467c0b7a.png)

**Comment by allthesignals** [comment]
Closed by da73cc76cd140884a0c349be2bf0e0533edb7088
