### ISSUE TITLE
Compare to list: Queens and Brooklyn should be switched

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#462]
Order should be
- New York City
- Bronx
- Brooklyn
- Manhattan
- Queens
- Staten Island

**Comment by EricaMaurer** [comment]
![Picture1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46d89d99379791acdeabf301b44fff9e2c4533317346f67275dde77aeb432959570b1aa841585910f9fd8d2ba2bf2e6c981e5ab38532022d8c6853beb2901eb80bbb258a4982b7bb834fc7e8382df5c6.jpg)

**Comment by andycochran** [comment]
Currently these are ordered by geotype… 
```sql
  (
    SELECT geoid, geotype, geogname AS label, 'City %26 Boroughs' AS typelabel
    FROM support_geoids
    WHERE geotype IN ('Boro2010', 'City2010')
    ORDER BY geotype DESC
  )
```

The easiest fix would be to `ORDER BY geogname ASC` and rename "New York City" to something that comes first, e.g. "All 5 Boroughs (NYC)."

**Comment by allthesignals** [comment]
That works - could try add a sort table that maps explicit order position to the geotype, then order by geotype AND geoname (nyc gets its own geotype after all). Alternatively, some front-end array manipulation would work, since this would require structural changes.
