### ISSUE TITLE
Census Profile > Relationship to Head of Household > "Total persons under 18 years" values are doubled (e.g. 200%)

### ISSUE THREAD

**Issue by JoelAAlvarez** [NYCPlanning/labs-nyc-factfinder#465]
User should see this value without doubling

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/35985577-f4610332-0cc4-11e8-9391-415b7c442427.png)

**Comment by EricaMaurer** [comment]
Data sent 2/12 to fix duplicate labels
