### ISSUE TITLE
Highlight bug, indent bug, space bug

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#477]
in Asian Subgroup: chinese, filipino, korean, and thai all have a space after the label in the database

in Sex and Age: male has a space after the label in the database
18 and over should be under 18 years (and data label should be changed too)-- this should be fixed by issue #467 but will need to check to confirm

in Population Density: Total population should be highlighted

in Household Type: Family households should not be indented

**Comment by allthesignals** [comment]
@EricaMaurer we're not clear on what should be happening and what is happening on this issue

**Comment by EricaMaurer** [comment]
These were the changes I made in #458 (in the wrong places)

The variables listed with an extra space in the database label are not appearing in the application. A space should be added to the code after the label or the space should be removed from the label name in the database

18 and over needs to be changed to under 18 years-- the data is not appearing in the app because it's currently using the wrong variable. This one should be fixed by #467, so may no longer be an issue

Total population in population density sub-section should be highlighted-- currently it is not highlighted

The indent from family households in household type sub-section should be removed

**Comment by andycochran** [comment]
- [ ] @EricaMaurer to give us a new decennial file w/o spaces. 
- [ ] @andycochran to fix indent and highlight

**Comment by EricaMaurer** [comment]
The file is too big to add here

**Comment by allthesignals** [comment]
This is fixed by updating the metadata which removes the spaces from the label names
