### ISSUE TITLE
Thematic Maps duplicate items

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-nyc-factfinder#507]
Thematic maps have duplicate items under the "Housing" section. Each item in the other sections also exists under "Housing."

<img src="https://user-images.githubusercontent.com/409279/36213082-c0dbd826-1173-11e8-98a4-39d288040b9e.png" width=300>

**Comment by allthesignals** [comment]
Hmmm is this is a priority for this week?

**Comment by andycochran** [comment]
Already fixed. :)
