### ISSUE TITLE
CV rule for graying should be applied to special variables

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#519]

**Comment by EricaMaurer** [comment]
![image](https://user-images.githubusercontent.com/32674674/36238786-d49e673e-11d2-11e8-913a-bd8ac52e0b37.png)

![image](https://user-images.githubusercontent.com/32674674/36238788-dd0ce472-11d2-11e8-81ba-a3bee945979c.png)

https://nyc-factfinder.planninglabs.nyc/profile/681/economic?comparator=3&reliability=true

**Comment by chriswhong** [comment]
We are currently defining `is_reliable` in the SQL, checking if `cv` > 20.  Then we do a bunch of additional calculations for special variables, which may change what cv ends up being in the response.

Recommend we remove the `is_reliable` step from SQL and add it as a close-to-final step before the response goes back to the client (after all the helper utilities have done their thing)

I need to get a local DB set up to develop on this.

**Comment by allthesignals** [comment]
@chriswhong the out of the box solution for this is to redefine all upstream and downstream special variables in the special calculations, which is what we're doing for a bunch of other things.
