### ISSUE TITLE
Comparison list bug

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#521]
When you select comparison area and then switch profiles.. 

comparison area remains selected (in the URL)

but comparison area name disappeared from box and cannot change selection

![image](https://user-images.githubusercontent.com/32674674/36239582-d2a282c0-11d8-11e8-9071-9c5eb5c9353b.png)

**Comment by allthesignals** [comment]
This is due to Carto throwing platform limit errors, and we will work to improve the bandwidth issues. Closing
