### ISSUE TITLE
Comparison area New Zealander percent and percent MOE not appearing

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#536]
![image](https://user-images.githubusercontent.com/32674674/36386226-0d756376-1563-11e8-84ff-ea7df55bb79f.png)

**Comment by EricaMaurer** [comment]
not fixed

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-09 at 11.12.20 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454fa6b7191a379ee0c2a53415d4ebc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e14b54a51a3360e471356e0a.png)

Fixed. The import script here https://github.com/NYCPlanning/labs-factfinder-db/blob/master/import.sh was truncating the wrong table, resulting in duplicates / old versions of the same rows. we were only getting the first off the top, which was the older vsion.
