### ISSUE TITLE
Ancestry total population MOE and CV should not be null for NYC and boros

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#537]
This is a data issue (has been sneaking by this whole time because nulls were displayed as 0)

In the data, the MOE and CV are null for NYC and boros-- should be 0.

Will need to send new data for this variable, unless there's another way to fix this.

![image](https://user-images.githubusercontent.com/32674674/36385986-5137f39a-1562-11e8-8e3e-73ef888854fc.png)

**Comment by EricaMaurer** [comment]
will be fixed with the updated data

**Comment by EricaMaurer** [comment]
not fixed

**Comment by EricaMaurer** [comment]
not fixed-- can we check that the latest version was loaded in and not an earlier version?

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-09 at 11.15.01 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454fa6b7191a379ee0c2a54415f4fbc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e14b54a6123760e475326e0a.png)

These are appearing now - closing.
