### ISSUE TITLE
0 percent change not appearing (single and multi geog)

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#538]
When sum and previous_sum are same value, percent change = 0.. this value is not appearing

Example: https://nyc-factfinder.planninglabs.nyc/profile/733/housing?charts=false&comparator=4104&mode=change&reliability=true

Selected Monthly Owner Costs as a Percentage of Household Income--> Housing unit without a mortgage --> 20.0 to 24.9 percent

![image](https://user-images.githubusercontent.com/32674674/36389653-e0b2f7d0-156d-11e8-9cbd-656da9121cfc.png)

**Comment by allthesignals** [comment]
Change Percent Estimate should say `0%` in this case, not null
