### ISSUE TITLE
Percentage point change not appearing for some languages

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#539]
When either (2006-2010 or 2012-2016) percent is null, percentage point change is not being calculated (sometimes). 

https://nyc-factfinder.planninglabs.nyc/profile/733/social?charts=false&comparator=4104&mode=change&reliability=true

![image](https://user-images.githubusercontent.com/32674674/36390020-692390ce-156f-11e8-8b87-e91884b01288.png)

![image](https://user-images.githubusercontent.com/32674674/36390300-a1cc3a24-1570-11e8-8a16-984c69ab264d.png)

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-05 at 10.27.26 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f66b7191a379ef0c2956415d48bc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e14f53a715336ae476336e0a.png)
^ calculation happens here

![Screen Shot 2018-03-05 at 10.28.04 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f66b7191a379ef0c2959415f4abc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e14f53a7153f63ef73376e0a.png)
^ but it doesn't happen here (and it should)

![Screen Shot 2018-03-05 at 10.28.41 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f66b7191a379ef0c2959415b4fbc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb2984dc259f349e14f53a7143464e572306e0a.png)
^ It doesn't happen for the bases (maybe)

**Comment by allthesignals** [comment]
The speak English less than "very well" variables aren't bases

**Comment by allthesignals** [comment]
These are working in my branch now:
![Screen Shot 2018-03-07 at 9.25.54 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f46b7191a371f1102e4f5a5b5edd3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19041c95df44be54e57a31b3767e07e2431.png)
![Screen Shot 2018-03-07 at 9.25.04 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f46b7191a371f1102e4f5f5b5edd3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44be54e57a31b3767e37e2431.png)
