### ISSUE TITLE
Clear Selection Bug

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-nyc-factfinder#54]
Clear selection is buggy when switching between selector types. 

To replicate: 

- Load the app
- Select a tract
- Switch to blocks
- Unselect one of the blocks
- Click "clear selection"
- Everything should clear; but instead, the blocks are all selected as they were when you changed modes

**Comment by andycochran** [comment]
You can also get into a mode where tracts and blocks are both highlighted. 

![image](https://user-images.githubusercontent.com/409279/32111501-ab570776-bb08-11e7-9f6d-0b43d5ba1480.png)

**Comment by andycochran** [comment]
Can this still be reproduced? 
Make sure clearing still works once #71 is closed.

**Comment by trbmcginnis** [comment]
Not seeing this bug anymore
