### ISSUE TITLE
Percentage point difference not appearing for some languages

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#540]
https://nyc-factfinder.planninglabs.nyc/profile/733/social?charts=false&comparator=4104&reliability=true
![image](https://user-images.githubusercontent.com/32674674/36390518-52716f3e-1571-11e8-9559-265ed8a89583.png)

https://nyc-factfinder.planninglabs.nyc/profile/37/social?charts=false&reliability=true
![image](https://user-images.githubusercontent.com/32674674/36390543-6e6187b0-1571-11e8-80cb-f83f4ee9bbfe.png)

**Comment by allthesignals** [comment]
Probably related to #539 - it's just pct point logic

**Comment by allthesignals** [comment]
@EricaMaurer we have a check for whether percent or _previous_percent_ are null... which seems wrong. Here is what it is:
`(and (eq data.percent null) (eq data.previous_percent null))`

I think it should be: 
`(and (eq data.percent null) (eq data.comparison_percent null))`

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-07 at 10.15.01 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f46b7191a379ef0c2a54415f4fbc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e14956a1143465e07e366e0a.png)

**Comment by EricaMaurer** [comment]
Great!

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-07 at 10.28.03 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f46b7191a379ef0c2959415f4dbc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e14956a2163661e675306e0a.png)
