### ISSUE TITLE
single geog: percentage point difference not appearing when selected area estimate is 0 (sometimes)

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#541]
Example: https://nyc-factfinder.planninglabs.nyc/profile/735/demographic?charts=false&comparator=SI07&mode=change&reliability=true

![image](https://user-images.githubusercontent.com/32674674/36405308-ffe60e9e-15bd-11e8-8d96-493ec377dc7f.png)

**Comment by allthesignals** [comment]
Probably related to #540 and #539

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-07 at 3.01.26 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f46b7191a37bf1122a4f5d595ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44be54857ac1a3f67e3742431.png)
