### ISSUE TITLE
single geog: percentage point moe not calculating correct value (change over time)

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#542]
Looks like it is pulling the value from selected area percent moe * 100

**Comment by allthesignals** [comment]
Is this percentage point MOE change over time for _every_ variable? Or just some?

**Comment by EricaMaurer** [comment]
every variable

**Comment by allthesignals** [comment]
```

**Comment by allthesignals** [comment]
I again think this comes down to the data publishing percents as display percents, requiring some differences between bt single calc and aggregate calc

**Comment by allthesignals** [comment]
Some of the significance codings look off.

**Comment by EricaMaurer** [comment]
examples are in #545 and #548 (change over time and difference)
