### ISSUE TITLE
single geog: percentage point change not appearing when 2006-2010 or 2012-2016 estimate is 0

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#543]
![Screen Shot 2018-03-05 at 10.31.47 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f66b7191a379ef0c2850415b49bc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb2984dc259f349e14f53a71a376ae571336e0a.png)

^ when either previous or current variable estimates are zero, the percentage point calculation doesn't get calculated and it should

**Comment by allthesignals** [comment]
This works now.

**Comment by allthesignals** [comment]
http://localhost:4200/profile/735/demographic?charts=false&comparator=SI07&reliability=true

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-07 at 3.23.33 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f46b7191a37bf110284f5c5c5ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44be54851a6113260e5702431.png)
