### ISSUE TITLE
single geog: 2006-2010 special variables $ need to be inflated

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#544]
Is there something that can be added to the code? Or do these adjusted values need to be in the data that gets pulled in?

My preference would be if we could add something to the code to inflate single geogs since the inflation will change each year but the 2006-2010 input data will not

**Comment by EricaMaurer** [comment]
will be fixed with the updated data

**Comment by allthesignals** [comment]
Updating data now, there are some issues with the data's column names. Spending some time resolving those and then this should be fixed.

**Comment by allthesignals** [comment]
@chriswhong need help doing this
