### ISSUE TITLE
single geog: fix percentage point change over time graying

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#548]
https://nyc-factfinder.planninglabs.nyc/profile/735/demographic?charts=false&comparator=SI07&mode=change&reliability=true

Examples where pctg pt change should not be gray: 30 to 34 year old, under 18 years

**Comment by EricaMaurer** [comment]
I think this has to do with the percent and percent MOE and the *100 issue.

So I think in the single profile query, percentage point change significance should just reference change percentage point est and change percentage point moe

-- change_percentage_point_significant --
      CASE
        WHEN (change_percentage_point_m < ABS(change_percentage_point)) THEN
          TRUE
        ELSE
          FALSE
      END AS change_percentage_point_significant

**Comment by allthesignals** [comment]
![Screen Shot 2018-03-05 at 10.34.16 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f66b7191a379ef0c2855415e48bc30254d58eeb9cb74fce36f34985619e8d8385720c43940aeb08a4beb05ba208d1b80b2b88a48c9fa2137a5dad11b61435c52dcbd4f3fb2984dc259f349e14f53a013316bee7e3f6e0a.png)

Percentage Point should _not_ be gray, it should be color-coded as significant. It maybe have something to do with the 100 percent calc - maybe the multi wasn't carried over to single

**Comment by allthesignals** [comment]
@EricaMaurer can I get help double-checking the math for significance? Heres what I have:
`(ABS((SQRT((POWER(coalesce(previous_percent_m, 0), 2) + POWER(coalesce(percent_m, 0), 2))))) > (percent - previous_percent))`

So, the percentage point change is significant when the left hand side is greater than the right-hand side. Should it be greaer than or less than? Thanks.

**Comment by allthesignals** [comment]
All the input values for these are true percentages

**Comment by EricaMaurer** [comment]
@allthesignals it should be significant if the MOE is less than the Est so your formula it should be less than.

But if the percents are going to cause a problem with multiplying by 100, you could just change the formula to reference the change est and MOE and not the actual percent columns.

**Comment by allthesignals** [comment]
cool - what would that look like? would previous_percent_m b just the margine of error?

**Comment by EricaMaurer** [comment]
Would it just be like this?

-- change_percentage_point_significant --
CASE
WHEN (change_percentage_point_m < ABS(change_percentage_point)) THEN
TRUE
ELSE
FALSE
END AS change_percentage_point_significant

Similar to the way change percent significant is set up.

**Comment by allthesignals** [comment]
Okay that fixes the column in question... gonna PR something
