### ISSUE TITLE
Reorder and make sure data in CSV download is accurate

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#565]

**Comment by allthesignals** [comment]
What order would you like them to be in? Need description ;) if you want some guidance on how to describe it, the issue template has guidelines. Thanks!

**Comment by allthesignals** [comment]
I se this is assigned to you - maybe it was meant for you later?

**Comment by EricaMaurer** [comment]
Ah yes. Sorry! Will get you that! I have questions about how some things are displayed too.

**Comment by EricaMaurer** [comment]
duplicate
