### ISSUE TITLE
Decennial: Numbers are doubled in  'Housing Occupancy' table

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#571]
![image](https://user-images.githubusercontent.com/32674674/37104553-040648a6-21fb-11e8-8e29-80dfa47776e7.png)

**Comment by allthesignals** [comment]
In all of them? Have you checked the data? It's weird that that's the only data point that is doubled. These aren't special variables so they are treated like every other variable. Is it the base total that's double or all variables in housing occupancy?

**Comment by allthesignals** [comment]
@JoelAAlvarez this issue was opened mid-week and I may not be able to get to solving whatever is behind this - I was hoping to have all the issues with things upfront so I could map out my week. Thanks.

**Comment by EricaMaurer** [comment]
It's happening to all variables in this table-- selected and comparison area and both time points.

**Comment by EricaMaurer** [comment]
It is just that sub-table

**Comment by EricaMaurer** [comment]
Link to profile where behavior is occurring: any geog selection..  but here's an example: https://nyc-factfinder.planninglabs.nyc/profile/851/census?charts=false&reliability=true

Name of variable(s) where behavior is occurring (or is it all variables?): decennial: all variables in the "Housing Occupancy" sub-table
- Total housing units
- Occupied housing units
- Vacant housing units
-- for rent
-- for sale only
-- rented or sold, not occupied
-- for seasonal, recreational, or occasional use
-- other vacant

- homeowner vacancy rate and rental vacancy rate are incorrect because they are using some of the above variables.

Is this a single geography selection or a multiple (aggregation) geography selection?: both

Which calculation is it (estimate, margin of error, percentage margin of error, difference margin of error, etc?): number-- selected and comparison area & 2000 and 2010

Is this in the change over time view or the current year view?: both

If change over time view, is it in 2006-2010 or 2012-2016 columns?: both 2000 and 2010

What is the value now and what should it be instead? What is the significance coding now and what should it be instead?: value for occupied housing units is appearing as 16,378. should be 8,189 (but all non-special variables are just doubled)

**Comment by allthesignals** [comment]
Thanks @EricaMaurer 

Looks like There are duplicates in the database and also doubling isn't in the data itself:
![image](https://user-images.githubusercontent.com/5004319/37233221-53ac5078-23c0-11e8-9936-8ed1ab83dd8e.png)

**Comment by allthesignals** [comment]
@EricaMaurer are you sure this is only in housing occupancy?

**Comment by EricaMaurer** [comment]
Yup

**Comment by allthesignals** [comment]
Of course it's duplicating because housing occupancy is duplicated - it does group summing.

**Comment by allthesignals** [comment]
These are no longer duplicated:

![image](https://user-images.githubusercontent.com/5004319/37233758-88fb5a60-23c2-11e8-8f99-140d15f55249.png)
