### ISSUE TITLE
add community board boundaries. 

### ISSUE THREAD

**Issue by noneck** [NYCPlanning/labs-nyc-factfinder#582]
#### User Story
As a community board member, I want to see community board districts so that I don't have to draw my own boundaries.

**Comment by chriswhong** [comment]
![image](https://user-images.githubusercontent.com/1833820/39014638-f035e330-43e8-11e8-8073-3adbc9e0ac4a.png)
These are located under "Advanced Options", along with several other administrative boundaries.

**Comment by noneck** [comment]
WOW! Shutting down a suggestion before even talking to the user and getting feedback?

I tried this and found it to be convoluted. Same goes for council districts. 

<img width="988" alt="screen shot 2018-04-19 at 15 49 15" src="https://user-images.githubusercontent.com/94735/39014985-f0a69f0c-43e9-11e8-8e17-f72371df5ef0.png">
