### ISSUE TITLE
Median top-coding

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#590]
### Link to profile where behavior is occurring: 
https://popfactfinder.planning.nyc.gov/profile/6219/housing 

### Is this a single geography selection or a multiple (aggregation) geography selection?: 
multiple

### Which profile is this in (Census, Demographic, Social, Economic, Housing)?: 
Housing

### Name of variable(s) where behavior is occurring (or is it all variables?):
median value and median gross rent

### Is this in the change over time view or the current year view?:
both

### If change over time view, is it in 2000, 2010, 2006-2010, or 2012-2016 columns?: 
2006-2010 and 2012-2016

### Which calculation is it (estimate, margin of error, cv, percent, percent margin of error, difference, change, etc?): 
estimate

### What is the value now and what should it be instead? 
I believe top-coding is reversed for 2006-2010 and 2012-2016 for median gross rent and 2012-2016 needs to be changed for median value.

The top-coding for median value and median gross rent (both in housing profile) are listed in the code, but are not appearing in the application as they should be. I believe the values/labeling for "earlier" and "later" might be reversed.

Median gross rent top-coding for 2012-2016 is $3,500 and for 2006-2010 is $2,000.
Right now $2,000+ is appearing for 2012-2016 data and $3,852+ is appearing for 2006-2010 data ($3,500 inflated).

**Comment by allthesignals** [comment]
2006-2010 Median Gross Rent is coming down as "upper", 2012-2016 is also coming down as "upper". The reversal is happening in the API.

**Comment by allthesignals** [comment]
@EricaMaurer do you think this is happening everywhere?

**Comment by allthesignals** [comment]
I'm seeing special configuration for top/bottom coding: https://github.com/NYCPlanning/labs-factfinder-api/blob/develop/metadata/top-bottom-codings.js#L195-L204

You have a PR open for this: https://github.com/NYCPlanning/labs-factfinder-api/pull/41/files

Here are the results of Gross Rent after applying your PR:
<img width="1256" alt="screen shot 2018-07-16 at 12 19 43 pm" src="https://user-images.githubusercontent.com/5004319/42770303-905e0c86-88f2-11e8-9756-f4ab2c94cd5f.png">

Median Value:
<img width="1255" alt="screen shot 2018-07-16 at 12 20 30 pm" src="https://user-images.githubusercontent.com/5004319/42770373-a5e5f596-88f2-11e8-9487-1ef03890ca12.png">

@EricaMaurer I understand that you listed the _top-coding_ for that variable, but would you know what the actual value for this geography + variable + time periods _should_ be? Do you think what I've posted looks right? Thx.

**Comment by EricaMaurer** [comment]
The results you posted don't look right for this area: https://popfactfinder.planning.nyc.gov/profile/6219/housing?mode=change&reliability=true

Median gross rent for 2006-2010 is right based on your results but if we could round it to $2,200+ that would be great (inflated from $2,000 to $2,201 and then rounded) and from my calculations, the 2012-2016 median gross rent for this area would be $2,717.

Median value for 2012-2016 for this area from my calculations would be $1,601,281

**Comment by allthesignals** [comment]
@EricaMaurer okay thanks

> round it to $2,200+
Separate issue, yeah?

> 2012-2016 median gross rent for this area would be $2,717
Sounds like something funky is going on with the median calculation. 

This issue is about top/bottom-coding, though - is it top-bottom-coding correctly now?

**Comment by EricaMaurer** [comment]
We would need to check other areas to see if it is accurately top-coding the 2012-2016 data since this area no longer falls in that category. But 2006-2010 is correct.

**Comment by allthesignals** [comment]
@EricaMaurer 

Thanks - do you know some areas that we can check this in? Once we can verify, we can close issue. Thx.

**Comment by allthesignals** [comment]
I see the correct top-coding happening for this area and new area: profile/7380/housing?mode=change. 

Closing.
