### ISSUE TITLE
If you start with block level, you don't get as much data

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-nyc-factfinder#65]
From a design perspective, how can it be made clear that some variables are not available

**Comment by trbmcginnis** [comment]
Not relevant anymore

**Comment by trbmcginnis** [comment]
Provide some feedback to the user that they could find data for that section if they change their selection, so if they aggregate up to a higher geography

**Comment by trbmcginnis** [comment]
Found another issue that had this same idea, so I just commented on it with your ideas for this one, going to close this one.
