### ISSUE TITLE
Demographics Tab - User can see "standard" report view

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#7]

**Comment by allthesignals** [comment]
Need to inner join metadata

**Comment by CeciliaCY** [comment]
The basic formulas for E , M, C, P, Z:
[Basic Formula Calculations.xlsx](https://github.com/NYCPlanning/labs-nyc-factfinder/files/1434226/Basic.Formula.Calculations.xlsx)

**Comment by CeciliaCY** [comment]
Mockups:
[mockups_and_charts_with_variables.xlsx](https://github.com/NYCPlanning/labs-nyc-factfinder/files/1434249/mockups_and_charts_with_variables.xlsx)

**Comment by CeciliaCY** [comment]
Mockups and charts with variables
[mockups_and_charts.xlsx](https://github.com/NYCPlanning/labs-nyc-factfinder/files/1434307/mockups_and_charts.xlsx)

**Comment by CeciliaCY** [comment]
New mock up 
[mockupofreportviews.xlsx](https://github.com/NYCPlanning/labs-nyc-factfinder/files/1438884/mockupofreportviews.xlsx)
