### ISSUE TITLE
Design and build tab content layout with mode switching

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#70]
Should include report header information, mode switching UI, map, chart, table, etc in a well-organized layout

Modes will be a sub-route on each tab

Index route should be a pointer to "standard" mode.
3 routes:

`/standard`
`/change` 
`/change-comparison`

**Comment by allthesignals** [comment]
Can alias index routes: https://guides.emberjs.com/v2.16.0/routing/defining-your-routes/#toc_index-routes

**Comment by chriswhong** [comment]
Main routes:

/report/census
/report/demographic
/report/social
/report/economic
/report/housing

**Comment by andycochran** [comment]
@chriswhong I just realized this is closed but we didn't address switching between standard/change/comparison modes. Should the routes instead be…

/report/[standard,change,comparison]/[census,demographic,social,economic,housing]

**Comment by chriswhong** [comment]
Wouldn't it be `/report/[census,demographic,social,economic,housing]/[standard,change,comparison]` ?

**Comment by andycochran** [comment]
Maybe. I'm not sure what the hierarchy _should_ be. But the customer's mockups seem to imply that `[standard,change,comparison]` is the higher level.

**Comment by chriswhong** [comment]
I think it can go either way, but I imagined you would switch modes AFTER you had already selected a top-level tab (demographic, etc).  Do we expect the mode to persist when the user switches tabs?  (Probably yes?)

**Comment by EricaMaurer** [comment]
It can probably go either way. If a user starts on the default data-tab.. and they switch the view and then switch data tabs, then the selected view type would remain. Or a user could start on the default data tab and then switch to another data tab and then switch views there. Either way, once a user selects a view type, they should continue to be in that view until they change it again.

**Comment by andycochran** [comment]
"Top-level tab" implies there's nothing above the tabs. I don't think that's true. The standard/change/comparison control changes the type of report you're looking at, where the tabs control what part of the report you're looking at. I think the standard/change/comparison control belongs above the tabs.

**Comment by andycochran** [comment]
I'll mock this up…
