### ISSUE TITLE
Cannot switch from block to PUMA/Neighborhood selection mode

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#71]
Currently the user can only go from blocks> tracts > NTA or PUMA.  We need to either prevent the user from switching to NTA/PUMA from block mode, or build in the ability to efficiently transition between any mode.

**Comment by chriswhong** [comment]
Reverse situation is the same, user cannot go from NTA/PUMA to block

**Comment by EricaMaurer** [comment]
If you select PUMAs and switch to CTs, census tracts are highlighted but the number of geogs selected is the number of PUMAs that were selected... and when you view profile, no data appears
