### ISSUE TITLE
Add report headers to each tab

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#93]
Introduce the data source
Indicate caveats with the data
Identify/Summarize the content of the tab (descriptive text)

**Comment by andycochran** [comment]
#### **Demographic Profile**
#### American Community Survey (ACS), 2011-2015 *
_tooltip: “Data associated with estimates of zero, top- and bottom-coded estimates, or Coefficients of Variation (CVs) of 20% or more are grayed out to signify poor statistical reliability. Comparisons and changes over time that are not statistically significant at a 90% confidence level are also grayed out.”_
(ACS data are derived from a survey and are subject to sampling variability)
(Grayed values are not statistically reliable) *
_tooltip: “Guidance on the ACS” and linking to https://www.census.gov/programs-surveys/acs/guidance.html_

---

_Demographic tab for change over time view:_
#### **Demographic Profile of Change Over Time**
#### American Community Survey (ACS), 2006-2010 to 2011-2015 *
-tooltip: “Guidance on the ACS” and linking to https://www.census.gov/programs-surveys/acs/guidance.html_
(ACS data are derived from a survey and are subject to sampling variability)
(Grayed values are not statistically reliable) *
_tooltip: “Data associated with estimates of zero, top- and bottom-coded estimates, or Coefficients of Variation (CVs) of 20% or more are grayed out to signify poor statistical reliability. Comparisons and changes over time that are not statistically significant at a 90% confidence level are also grayed out.”_

---

_Census tab for standard view:_
#### **Demographic and Housing Profile**
#### Decennial Census, 2010 *
_tooltip: “2010 Census, Summary File 1” links to
https://www.census.gov/programs-surveys/decennial-census/guidance/2010.html_

---

_Census tab for change over time view:_
#### **Demographic and Housing Profile of Change Over Time**
#### Decennial Census, 2000-2010 *
_tooltip: “2010 Census, Summary File 1 and 2000 Census, Summary File 1” first half links to https://www.census.gov/programs-surveys/decennial-census/guidance/2010.html and second half links to https://www.census.gov/programs-surveys/decennial-census/guidance/2000.html_
