### ISSUE TITLE
Population Pyramid Improvements

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-nyc-factfinder#94]
- MOE bars need to end at 0 (no negative MOE if MOE is larger than the estimate bar) (same for 100%)
- Refactor chart to use percentages natively
- Show percentages +pmoe first, then estimates +emoe (in the hover text)
- Colors - @andycochran to iterate on some color choices 
- Update top Male and Female Labels

Big One:
- Add comparison area bars (discussed using a smaller bar below the main bar OR a circle with a MOE bar)

**Comment by EricaMaurer** [comment]
- use same color for both males & females
- more prominent coloring for selection area
- reverse coloring for estimates & MOEs (estimates darker than MOEs)
- thinner lines for selection area MOE
- open circles with thin lines for comparison area MOE
- slight transparency for comparison area so selection area is more prominent

**Comment by andycochran** [comment]
If we want the same color for male and female, I'd suggest we use the color palette from Community Profiles: 

![image](https://user-images.githubusercontent.com/409279/32614851-26229b04-c53c-11e7-9767-fdb8189345b8.png)

**Comment by EricaMaurer** [comment]
Which color? The gray wouldn't work for us because gray is being used to show that the data is not reliable in the reports. The orange or the blue would be ok though.

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/32622398-b51518a0-c550-11e7-8c59-336fedd4e6d5.png)

**Comment by EricaMaurer** [comment]
I like the colors, but can the selected area MOE bars be a darker shade of the blue instead of gray? Gray means something in the report and don't think it should be used in the charts signifying something else.

**Comment by andycochran** [comment]
I also think vertical line might be better than a open circle. 

![image](https://user-images.githubusercontent.com/409279/32622610-6b898c1a-c551-11e7-8e27-aa3cefd54df8.png)

**Comment by andycochran** [comment]
Darker transparent blue (instead of black) MOEs: 

![image](https://user-images.githubusercontent.com/409279/32622734-dbe37b24-c551-11e7-8dd3-5c500d189fea.png)

**Comment by JoelAAlvarez** [comment]
I prefer non-transparent circles, with white cores, to represent the estimates.

**Comment by EricaMaurer** [comment]
The darker transparent blue still looks slightly gray to me--- maybe a different shade or less transparent?
